import { Question } from "../types/Question";

export const questionList: Question[] = [
    //FÁCEIS
    { id: 1, category: "anime", answers: ["Naruto"], imageUrl: "naruto.jpg" },
    { id: 2, category: "anime", answers: ["One Piece"], imageUrl: "one_piece.jpg" },
    { id: 3, category: "anime", answers: ["Attack on Titan"], imageUrl: "attack_on_titan.jpg" },
    { id: 4, category: "anime", answers: ["Fullmetal Alchemist"], imageUrl: "fullmetal_alchemist.jpg" },
    { id: 5, category: "anime", answers: ["Death Note"], imageUrl: "death_note.jpg" },
    { id: 6, category: "anime", answers: ["Dragon Ball Z"], imageUrl: "dragon_ball_z.jpg" },
    { id: 7, category: "anime", answers: ["My Hero Academia"], imageUrl: "my_hero_academia.jpg" },
    { id: 8, category: "anime", answers: ["Demon Slayer"], imageUrl: "demon_slayer.jpg" },
    { id: 9, category: "anime", answers: ["Tokyo Ghoul"], imageUrl: "tokyo_ghoul.jpg" },
    { id: 10, category: "anime", answers: ["Sword Art Online"], imageUrl: "sword_art_online.jpg" },
    { id: 11, category: "anime", answers: ["Bleach"], imageUrl: "bleach.jpg" },
    { id: 12, category: "anime", answers: ["Fairy Tail"], imageUrl: "fairy_tail.jpg" },
    { id: 13, category: "anime", answers: ["Cowboy Bebop"], imageUrl: "cowboy_bepop.jpg" },
    { id: 14, category: "anime", answers: ["Neon Genesis Evangelion"], imageUrl: "neon_genesis_evangelion.jpg" },
    { id: 15, category: "anime", answers: ["JoJo's Bizarre Adventure"], imageUrl: "jojo.jpg" },
    { id: 16, category: "anime", answers: ["Hunter x Hunter"], imageUrl: "hunter_x_hunter.jpg" },
    { id: 17, category: "anime", answers: ["Black Clover"], imageUrl: "black_clover.jpg" },
    { id: 18, category: "anime", answers: ["Gintama"], imageUrl: "gintama.jpg" },
    { id: 19, category: "anime", answers: ["Mob Psycho 100"], imageUrl: "mob_psycho_100.jpg" },
    { id: 20, category: "anime", answers: ["The Seven Deadly Sins"], imageUrl: "seven_deadly_sins.jpg" },
    { id: 21, category: "pokemon", answers: ["Bulbasaur"], imageUrl: "bulbasaur.jpg" },
    { id: 22, category: "pokemon", answers: ["Ivysaur"], imageUrl: "ivysaur.jpg" },
    { id: 23, category: "pokemon", answers: ["Venusaur"], imageUrl: "venusaur.jpg" },
    { id: 24, category: "pokemon", answers: ["Charmander"], imageUrl: "charmander.jpg" },
    { id: 25, category: "pokemon", answers: ["Charmeleon"], imageUrl: "charmeleon.jpg" },
    { id: 26, category: "pokemon", answers: ["Charizard"], imageUrl: "charizard.jpg" },
    { id: 27, category: "pokemon", answers: ["Squirtle"], imageUrl: "squirtle.jpg" },
    { id: 28, category: "pokemon", answers: ["Wartortle"], imageUrl: "wartortle.jpg" },
    { id: 29, category: "pokemon", answers: ["Blastoise"], imageUrl: "blastoise.jpg" },
    { id: 30, category: "pokemon", answers: ["Pikachu"], imageUrl: "pikachu.jpg" },
    { id: 31, category: "pokemon", answers: ["Raichu"], imageUrl: "raichu.jpg" },
    { id: 32, category: "pokemon", answers: ["Jigglypuff"], imageUrl: "jigglypuff.jpg" },
    { id: 33, category: "pokemon", answers: ["Meowth"], imageUrl: "meowth.jpg" },
    { id: 34, category: "pokemon", answers: ["Psyduck"], imageUrl: "psyduck.jpg" },
    { id: 35, category: "pokemon", answers: ["Machop"], imageUrl: "machop.jpg" },
    { id: 36, category: "pokemon", answers: ["Geodude"], imageUrl: "geodude.jpg" },
    { id: 37, category: "pokemon", answers: ["Eevee"], imageUrl: "eevee.jpg" },
    { id: 38, category: "pokemon", answers: ["Snorlax"], imageUrl: "snorlax.jpg" },
    { id: 39, category: "pokemon", answers: ["Mewtwo"], imageUrl: "mewtwo.jpg" },
    { id: 40, category: "pokemon", answers: ["Magikarp"], imageUrl: "magikarp.jpg" },
    { id: 41, category: "characters", answers: ["Mario"], imageUrl: "mario.jpg" },
    { id: 42, category: "characters", answers: ["Luigi"], imageUrl: "luigi.jpg" },
    { id: 43, category: "characters", answers: ["Shadow"], imageUrl: "shadow.jpg" },
    { id: 44, category: "characters", answers: ["Link"], imageUrl: "link.jpg" },
    { id: 45, category: "characters", answers: ["Ash Ketchum"], imageUrl: "ash_ketchum.jpg" },
    { id: 46, category: "characters", answers: ["Killer Bee"], imageUrl: "killer_bee.jpg" },
    { id: 47, category: "characters", answers: ["Goku Black"], imageUrl: "goku_black.jpg" },
    { id: 48, category: "characters", answers: ["Sailor Moon"], imageUrl: "sailor_moon.jpg" },
    { id: 49, category: "characters", answers: ["Batman"], imageUrl: "batman.jpg" },
    { id: 50, category: "characters", answers: ["Homem de Ferro"], imageUrl: "homem_de_ferro.jpg" },
    { id: 51, category: "characters", answers: ["Capitão América"], imageUrl: "capitao_america.jpg" },
    { id: 52, category: "characters", answers: ["Thor"], imageUrl: "thor.jpg" },
    { id: 53, category: "characters", answers: ["Lara Croft"], imageUrl: "lara_croft.jpg" },
    { id: 54, category: "characters", answers: ["Kratos"], imageUrl: "kratos.jpg" },
    { id: 55, category: "characters", answers: ["Master Chief"], imageUrl: "master_chief.jpg" },
    { id: 56, category: "characters", answers: ["Solid Snake"], imageUrl: "solid_snake.jpg" },
    { id: 57, category: "characters", answers: ["Yoshi"], imageUrl: "yoshi.jpg" },
    { id: 58, category: "characters", answers: ["Donkey Kong"], imageUrl: "donkey_kong.jpg" },
    { id: 59, category: "characters", answers: ["Kirby"], imageUrl: "kirby.jpg" },
    { id: 60, category: "characters", answers: ["Rock Lee"], imageUrl: "rock_lee.jpg" },
    { id: 61, category: "movies", answers: ["Inception"], imageUrl: "inception.jpg" },
    { id: 62, category: "movies", answers: ["Interstelar"], imageUrl: "interstelar.jpg" },
    { id: 63, category: "movies", answers: ["De Volta Para o Futuro"], imageUrl: "de_volta_para_o_futuro.jpg" },
    { id: 64, category: "movies", answers: ["Forrest Gump"], imageUrl: "forrest_gump.jpg" },
    { id: 66, category: "movies", answers: ["Pulp Fiction"], imageUrl: "pulp_fiction.jpg" },
    { id: 67, category: "movies", answers: ["Star Wars"], imageUrl: "star_wars.jpg" },
    { id: 68, category: "movies", answers: ["Matrix"], imageUrl: "matrix.jpg" },
    { id: 69, category: "movies", answers: ["Titanic"], imageUrl: "titanic.jpg" },
    { id: 70, category: "movies", answers: ["Gladiador"], imageUrl: "gladiador.jpg" },
    { id: 71, category: "movies", answers: ["Jurassic Park"], imageUrl: "jurassic_park.jpg" },
    { id: 72, category: "movies", answers: ["Avatar"], imageUrl: "avatar.jpg" },
    { id: 73, category: "movies", answers: ["O Rei Leão"], imageUrl: "o_rei_leao.jpg" },
    { id: 74, category: "movies", answers: ["Homem-Aranha 3"], imageUrl: "homem_aranha_3.jpg" },
    { id: 75, category: "movies", answers: ["Coringa"], imageUrl: "coringa.jpg" },
    { id: 76, category: "movies", answers: ["Os Vingadores"], imageUrl: "os_vingadores.jpg" },
    { id: 77, category: "movies", answers: ["Harry Potter"], imageUrl: "harry_potter.jpg" },
    { id: 78, category: "movies", answers: ["Brilho Eterno de uma Mente Sem Lembranças"], imageUrl: "brilho_eterno.jpg" },
    { id: 79, category: "movies", answers: ["Cidadão Kane"], imageUrl: "cidadao_kane.jpg" },
    { id: 80, category: "movies", answers: ["O Grande Lebowski"], imageUrl: "o_grande_lebowski.jpg" },
    { id: 81, category: "games", answers: ["The Witcher 3"], imageUrl: "the_witcher_3.jpg" },
    { id: 82, category: "games", answers: ["Red Dead Redemption 2"], imageUrl: "red_dead_redemption_2.jpg" },
    { id: 83, category: "games", answers: ["The Last of Us"], imageUrl: "the_last_of_us.jpg" },
    { id: 84, category: "games", answers: ["God of War"], imageUrl: "god_of_war.jpg" },
    { id: 85, category: "games", answers: ["Minecraft"], imageUrl: "minecraft.jpg" },
    { id: 86, category: "games", answers: ["Fortnite"], imageUrl: "fortnite.jpg" },
    { id: 87, category: "games", answers: ["League of Legends"], imageUrl: "league_of_legends.jpg" },
    { id: 88, category: "games", answers: ["Overwatch"], imageUrl: "overwatch.jpg" },
    { id: 89, category: "games", answers: ["Cyberpunk 2077"], imageUrl: "cyberpunk_2077.jpg" },
    { id: 90, category: "games", answers: ["Elden Ring"], imageUrl: "elden_ring.jpg" },
    { id: 91, category: "games", answers: ["Hollow Knight"], imageUrl: "hollow_knight.jpg" },
    { id: 92, category: "games", answers: ["Dark Souls 2"], imageUrl: "dark_souls_2.jpg" },
    { id: 93, category: "games", answers: ["Super Mario Odyssey"], imageUrl: "super_mario_odyssey.jpg" },
    { id: 94, category: "games", answers: ["Pokémon Yellow"], imageUrl: "pokemon_yellow.jpg" },
    { id: 95, category: "games", answers: ["Doom Eternal"], imageUrl: "doom_eternal.jpg" },
    { id: 96, category: "games", answers: ["Resident Evil 7"], imageUrl: "resident_evil_7.jpg" },
    { id: 97, category: "games", answers: ["Final Fantasy 7"], imageUrl: "final_fantasy_7.jpg" },
    { id: 98, category: "games", answers: ["Terraria"], imageUrl: "terraria.jpg" },
    { id: 99, category: "games", answers: ["Sonic 2"], imageUrl: "sonic_2.jpg" },
    { id: 100, category: "games", answers: ["Cuphead"], imageUrl: "cuphead.jpg" },
    { id: 101, category: "music", answers: ["Queen"], imageUrl: "queen.jpg" },
    { id: 102, category: "music", answers: ["The Beatles"], imageUrl: "the_beatles.jpg" },
    { id: 103, category: "music", answers: ["Michael Jackson"], imageUrl: "michael_jackson.jpg" },
    { id: 104, category: "music", answers: ["Madonna"], imageUrl: "madonna.jpg" },
    { id: 105, category: "music", answers: ["Elvis Presley"], imageUrl: "elvis_presley.jpg" },
    { id: 106, category: "music", answers: ["Beyoncé"], imageUrl: "beyonce.jpg" },
    { id: 107, category: "music", answers: ["Taylor Swift"], imageUrl: "taylor_swift.jpg" },
    { id: 108, category: "music", answers: ["Adele"], imageUrl: "adele.jpg" },
    { id: 109, category: "music", answers: ["Drake"], imageUrl: "drake.jpg" },
    { id: 110, category: "music", answers: ["Player Tauz"], imageUrl: "player_tauz.jpg" },
    { id: 111, category: "music", answers: ["Katy Perry"], imageUrl: "katy_perry.jpg" },
    { id: 112, category: "music", answers: ["Bruno Mars"], imageUrl: "bruno_mars.jpg" },
    { id: 113, category: "music", answers: ["Rihanna"], imageUrl: "rihanna.jpg" },
    { id: 114, category: "music", answers: ["Eminem"], imageUrl: "eminem.jpg" },
    { id: 115, category: "music", answers: ["Billie Eilish"], imageUrl: "billie_eilish.jpg" },
    { id: 116, category: "music", answers: ["Coldplay"], imageUrl: "coldplay.jpg" },
    { id: 117, category: "music", answers: ["Anitta"], imageUrl: "anitta.jpg" },
    { id: 118, category: "music", answers: ["Linkin Park"], imageUrl: "linkin_park.jpg" },
    { id: 119, category: "music", answers: ["Nirvana"], imageUrl: "nirvana.jpg" },
    { id: 120, category: "music", answers: ["Luan Santana"], imageUrl: "luan_santana.jpg" },
    { id: 121, category: "tvShows", answers: ["Breaking Bad"], imageUrl: "breaking_bad.jpg" },
    { id: 122, category: "tvShows", answers: ["Game of Thrones"], imageUrl: "game_of_thrones.jpg" },
    { id: 123, category: "tvShows", answers: ["Stranger Things"], imageUrl: "stranger_things.jpg" },
    { id: 124, category: "tvShows", answers: ["The Crown"], imageUrl: "the_crown.jpg" },
    { id: 125, category: "tvShows", answers: ["The Mandalorian"], imageUrl: "the_mandalorian.jpg" },
    { id: 126, category: "tvShows", answers: ["Friends"], imageUrl: "friends.jpg" },
    { id: 127, category: "tvShows", answers: ["The Office"], imageUrl: "the_office.jpg" },
    { id: 128, category: "tvShows", answers: ["Sherlock"], imageUrl: "sherlock.jpg" },
    { id: 129, category: "tvShows", answers: ["Westworld"], imageUrl: "westworld.jpg" },
    { id: 130, category: "tvShows", answers: ["Peaky Blinders"], imageUrl: "peaky_blinders.jpg" },
    { id: 131, category: "tvShows", answers: ["The Witcher"], imageUrl: "the_witcher.jpg" },
    { id: 132, category: "tvShows", answers: ["House of Cards"], imageUrl: "house_of_cards.jpg" },
    { id: 133, category: "tvShows", answers: ["Better Call Saul"], imageUrl: "better_call_saul.jpg" },
    { id: 134, category: "tvShows", answers: ["Black Mirror"], imageUrl: "black_mirror.jpg" },
    { id: 135, category: "tvShows", answers: ["Narcos"], imageUrl: "narcos.jpg" },
    { id: 136, category: "tvShows", answers: ["The Boys"], imageUrl: "the_boys.jpg" },
    { id: 137, category: "tvShows", answers: ["Loki"], imageUrl: "loki.jpg" },
    { id: 138, category: "tvShows", answers: ["WandaVision"], imageUrl: "wandavision.jpg" },
    { id: 139, category: "tvShows", answers: ["Lupin"], imageUrl: "lupin.jpg" },
    { id: 140, category: "tvShows", answers: ["Round 6"], imageUrl: "round_6.jpg" },
    { id: 141, category: "cartoons", answers: ["Bob Esponja"], imageUrl: "bob_esponja.jpg" },
    { id: 142, category: "cartoons", answers: ["Pica-Pau"], imageUrl: "pica_pau.jpg" },
    { id: 143, category: "cartoons", answers: ["Tom e Jerry"], imageUrl: "tom_e_jerry.jpg" },
    { id: 144, category: "cartoons", answers: ["O Incrível Mundo de Gumball"], imageUrl: "o_incrivel_mundo_de_gumball.jpg" },
    { id: 145, category: "cartoons", answers: ["Hora de Aventura"], imageUrl: "hora_de_aventura.jpg" },
    { id: 146, category: "cartoons", answers: ["Os Padrinhos Mágicos"], imageUrl: "os_padrinhos_magicos.jpg" },
    { id: 147, category: "cartoons", answers: ["Os Simpsons"], imageUrl: "os_simpsons.jpg" },
    { id: 148, category: "cartoons", answers: ["Futurama"], imageUrl: "futurama.jpg" },
    { id: 149, category: "cartoons", answers: ["Rick e Morty"], imageUrl: "rick_e_morty.jpg" },
    { id: 150, category: "cartoons", answers: ["Ursinho Pooh"], imageUrl: "ursinho_pooh.jpg" },
    { id: 151, category: "cartoons", answers: ["Apenas um Show"], imageUrl: "apenas_um_show.jpg" },
    { id: 152, category: "cartoons", answers: ["Sonic Satam"], imageUrl: "sonic_satam.jpg" },
    { id: 153, category: "cartoons", answers: ["As Meninas Superpoderosas"], imageUrl: "as_meninas_superpoderosas.jpg" },
    { id: 154, category: "cartoons", answers: ["Ben 10"], imageUrl: "ben_10.jpg" },
    { id: 155, category: "cartoons", answers: ["Phineas e Ferb"], imageUrl: "phineas_e_ferb.jpg" },
    { id: 156, category: "cartoons", answers: ["Slugterrâneo"], imageUrl: "slugterraneo.jpg" },
    { id: 157, category: "cartoons", answers: ["Kid vs Cat"], imageUrl: "kid_vs_cat.jpg" },
    { id: 158, category: "cartoons", answers: ["Liga da Justiça"], imageUrl: "liga_da_justica.jpg" },
    { id: 159, category: "cartoons", answers: ["Super Choque"], imageUrl: "super_choque.jpg" },
    { id: 160, category: "cartoons", answers: ["Peixonauta"], imageUrl: "peixonauta.jpg" },
    { id: 161, category: "logo", answers: ["Nike"], imageUrl: "nike.jpg" },
    { id: 162, category: "logo", answers: ["Adidas"], imageUrl: "adidas.jpg" },
    { id: 163, category: "logo", answers: ["Apple"], imageUrl: "apple.jpg" },
    { id: 164, category: "logo", answers: ["NVIDIA"], imageUrl: "nvidia.jpg" },
    { id: 165, category: "logo", answers: ["Starbucks"], imageUrl: "starbucks.jpg" },
    { id: 166, category: "logo", answers: ["Pepsi"], imageUrl: "pepsi.jpg" },
    { id: 167, category: "logo", answers: ["Kabum"], imageUrl: "kabum.jpg" },
    { id: 168, category: "logo", answers: ["AMD"], imageUrl: "amd.jpg" },
    { id: 169, category: "logo", answers: ["Android"], imageUrl: "android.jpg" },
    { id: 170, category: "logo", answers: ["Microsoft"], imageUrl: "microsoft.jpg" },
    { id: 171, category: "logo", answers: ["Facebook"], imageUrl: "facebook.jpg" },
    { id: 172, category: "logo", answers: ["Twitter"], imageUrl: "twitter.jpg" },
    { id: 173, category: "logo", answers: ["YouTube Music"], imageUrl: "youtube_music.jpg" },
    { id: 174, category: "logo", answers: ["Amazon"], imageUrl: "amazon.jpg" },
    { id: 175, category: "logo", answers: ["Samsung"], imageUrl: "samsung.jpg" },
    { id: 176, category: "logo", answers: ["Toyota"], imageUrl: "toyota.jpg" },
    { id: 177, category: "logo", answers: ["BMW"], imageUrl: "bmw.jpg" },
    { id: 178, category: "logo", answers: ["Volkswagen"], imageUrl: "volkswagen.jpg" },
    { id: 179, category: "logo", answers: ["Audi"], imageUrl: "audi.jpg" },
    { id: 180, category: "logo", answers: ["Honda"], imageUrl: "honda.jpg" },
    { id: 181, category: "flag", answers: ["Brasil"], imageUrl: "brasil.jpg" },
    { id: 182, category: "flag", answers: ["Estados Unidos"], imageUrl: "estados_unidos.jpg" },
    { id: 183, category: "flag", answers: ["Japão"], imageUrl: "japao.jpg" },
    { id: 184, category: "flag", answers: ["Alemanha"], imageUrl: "alemanha.jpg" },
    { id: 185, category: "flag", answers: ["Egito"], imageUrl: "egito.jpg" },
    { id: 186, category: "flag", answers: ["Itália"], imageUrl: "italia.jpg" },
    { id: 187, category: "flag", answers: ["Reino Unido"], imageUrl: "reino_unido.jpg" },
    { id: 188, category: "flag", answers: ["Canadá"], imageUrl: "canada.jpg" },
    { id: 189, category: "flag", answers: ["China"], imageUrl: "china.jpg" },
    { id: 190, category: "flag", answers: ["Índia"], imageUrl: "india.jpg" },
    { id: 191, category: "flag", answers: ["Suriname"], imageUrl: "suriname.jpg" },
    { id: 192, category: "flag", answers: ["Austrália"], imageUrl: "australia.jpg" },
    { id: 193, category: "flag", answers: ["México"], imageUrl: "mexico.jpg" },
    { id: 194, category: "flag", answers: ["Argentina"], imageUrl: "argentina.jpg" },
    { id: 195, category: "flag", answers: ["África do Sul"], imageUrl: "africa_do_sul.jpg" },
    { id: 196, category: "flag", answers: ["Coreia do Norte"], imageUrl: "coreia_do_norte.jpg" },
    { id: 197, category: "flag", answers: ["Espanha"], imageUrl: "espanha.jpg" },
    { id: 198, category: "flag", answers: ["Suécia"], imageUrl: "suecia.jpg" },
    { id: 199, category: "flag", answers: ["Noruega"], imageUrl: "noruega.jpg" },
    { id: 200, category: "flag", answers: ["Suiça"], imageUrl: "suica.jpg" },
    { id: 201, category: "soccer", answers: ["Barcelona"], imageUrl: "barcelona.jpg" },
    { id: 202, category: "soccer", answers: ["Real Madrid"], imageUrl: "real_madrid.jpg" },
    { id: 203, category: "soccer", answers: ["Manchester United"], imageUrl: "manchester_united.jpg" },
    { id: 204, category: "soccer", answers: ["Liverpool"], imageUrl: "liverpool.jpg" },
    { id: 205, category: "soccer", answers: ["Juventus"], imageUrl: "juventus.jpg" },
    { id: 206, category: "soccer", answers: ["Fluminense"], imageUrl: "fluminense.jpg" },
    { id: 207, category: "soccer", answers: ["Corinthians"], imageUrl: "corinthians.jpg" },
    { id: 208, category: "soccer", answers: ["LDU"], imageUrl: "ldu.jpg" },
    { id: 209, category: "soccer", answers: ["Santos"], imageUrl: "santos.jpg" },
    { id: 210, category: "soccer", answers: ["Inter de Milão"], imageUrl: "inter_de_milao.jpg" },
    { id: 211, category: "soccer", answers: ["Boca Júniors"], imageUrl: "boca_juniors.jpg" },
    { id: 212, category: "soccer", answers: ["Chelsea"], imageUrl: "chelsea.jpg" },
    { id: 213, category: "soccer", answers: ["Arsenal"], imageUrl: "arsenal.jpg" },
    { id: 214, category: "soccer", answers: ["River Plate"], imageUrl: "river_plate.jpg" },
    { id: 215, category: "soccer", answers: ["Independiente"], imageUrl: "independiente.jpg" },
    { id: 216, category: "soccer", answers: ["San Lorenzo"], imageUrl: "san_lorenzo.jpg" },
    { id: 217, category: "soccer", answers: ["Grêmio"], imageUrl: "gremio.jpg" },
    { id: 218, category: "soccer", answers: ["Internacional"], imageUrl: "internacional.jpg" },
    { id: 219, category: "soccer", answers: ["Atlético Mineiro"], imageUrl: "atletico_mineiro.jpg" },
    { id: 220, category: "soccer", answers: ["Bayer Leverkusen"], imageUrl: "bayer_leverkusen.jpg" },
    { id: 221, category: "fruits", answers: ["Maçã"], imageUrl: "maca.jpg" },
    { id: 222, category: "fruits", answers: ["Banana"], imageUrl: "banana.jpg" },
    { id: 223, category: "fruits", answers: ["Laranja"], imageUrl: "laranja.jpg" },
    { id: 224, category: "fruits", answers: ["Morango"], imageUrl: "morango.jpg" },
    { id: 225, category: "fruits", answers: ["Abacaxi"], imageUrl: "abacaxi.jpg" },
    { id: 226, category: "fruits", answers: ["Uva"], imageUrl: "uva.jpg" },
    { id: 227, category: "fruits", answers: ["Melancia"], imageUrl: "melancia.jpg" },
    { id: 228, category: "fruits", answers: ["Pera"], imageUrl: "pera.jpg" },
    { id: 229, category: "fruits", answers: ["Tangerina"], imageUrl: "tangerina.jpg" },
    { id: 230, category: "fruits", answers: ["Framboesa"], imageUrl: "framboesa.jpg" },
    { id: 231, category: "animals", answers: ["Onça"], imageUrl: "onca.jpg" },
    { id: 232, category: "animals", answers: ["Urso Polar"], imageUrl: "urso_polar.jpg" },
    { id: 233, category: "animals", answers: ["Coala"], imageUrl: "coala.jpg" },
    { id: 234, category: "animals", answers: ["Hipopótamo"], imageUrl: "hipopotamo.jpg" },
    { id: 235, category: "animals", answers: ["Rinoceronte"], imageUrl: "rinoceronte.jpg" },
    { id: 236, category: "animals", answers: ["Chita"], imageUrl: "chita.jpg" },
    { id: 237, category: "animals", answers: ["Boto"], imageUrl: "boto.jpg" },
    { id: 238, category: "animals", answers: ["Águia"], imageUrl: "aguia.jpg" },
    { id: 239, category: "animals", answers: ["Falcão"], imageUrl: "falcao.jpg" },
    { id: 240, category: "animals", answers: ["Crocodilo"], imageUrl: "crocodilo.jpg" },
    { id: 241, category: "animals", answers: ["Golfinho"], imageUrl: "golfinho.jpg" },
    { id: 242, category: "animals", answers: ["Jacaré"], imageUrl: "jacare.jpg" },
    { id: 243, category: "characters", answers: ["Pepsiman"], imageUrl: "pepsiman.jpg" },
    { id: 244, category: "characters", answers: ["Shisui Uchiha"], imageUrl: "shisui_uchiha.jpg" },
    { id: 245, category: "characters", answers: ["Jaco"], imageUrl: "jaco.jpg" },
    { id: 246, category: "characters", answers: ["Law"], imageUrl: "law.jpg" },
    { id: 247, category: "characters", answers: ["Gol D. Roger"], imageUrl: "gol_d_roger.jpg" },
    { id: 248, category: "characters", answers: ["Cooler"], imageUrl: "cooler.jpg" },
    { id: 249, category: "characters", answers: ["Kefla"], imageUrl: "kefla.jpg" },
    { id: 250, category: "characters", answers: ["Nail"], imageUrl: "nail.jpg" },
    { id: 251, category: "characters", answers: ["Boa Hancock"], imageUrl: "boa_hancock.jpg" },
    { id: 252, category: "characters", answers: ["Turles"], imageUrl: "turles.jpg" },
    { id: 253, category: "characters", answers: ["Zarbon"], imageUrl: "zarbon.jpg" },
    { id: 254, category: "characters", answers: ["Bardock"], imageUrl: "bardock.jpg" },
    { id: 255, category: "games", answers: ["Pepsiman"], imageUrl: "pepsiman_ps1.jpg" },
    { id: 256, category: "games", answers: ["Minecraft Legends"], imageUrl: "minecraft_legends.jpg" },
    { id: 257, category: "games", answers: ["Minecraft Dungeons"], imageUrl: "minecraft_dungeons.jpg" },
    { id: 258, category: "games", answers: ["Minecraft Story Mode"], imageUrl: "minecraft_story_mode.jpg" },
    { id: 259, category: "games", answers: ["Forza Horizon"], imageUrl: "forza_horizon.jpg" },
    { id: 260, category: "games", answers: ["Forza Horizon 3"], imageUrl: "forza_horizon_3.jpg" },
    { id: 261, category: "games", answers: ["Need For Speed Most Wanted"], imageUrl: "need_for_speed_most_wanted.jpg" },
    { id: 262, category: "games", answers: ["Need For Speed Underground 2"], imageUrl: "need_for_speed_underground_2.jpg" },
    { id: 263, category: "games", answers: ["Midnight Club 3"], imageUrl: "midnight_club_3.jpg" },
    { id: 264, category: "games", answers: ["Burnout Paradise"], imageUrl: "burnout_paradise.jpg" },
    { id: 265, category: "games", answers: ["Burnout Revenge"], imageUrl: "burnout_revenge.jpg" },
    { id: 266, category: "pokemon", answers: ["Celebi"], imageUrl: "celebi.jpg" },
    { id: 267, category: "pokemon", answers: ["Jirachi"], imageUrl: "jirachi.jpg" },
    { id: 268, category: "pokemon", answers: ["Deoxys"], imageUrl: "deoxys.jpg" },
    { id: 269, category: "pokemon", answers: ["Phione"], imageUrl: "phione.jpg" },
    { id: 270, category: "pokemon", answers: ["Manaphy"], imageUrl: "manaphy.jpg" },
    { id: 271, category: "pokemon", answers: ["Darkrai"], imageUrl: "darkrai.jpg" },
    { id: 272, category: "pokemon", answers: ["Totodile"], imageUrl: "totodile.jpg" },
    { id: 273, category: "pokemon", answers: ["Cyndaquil"], imageUrl: "cyndaquil.jpg" },
    { id: 274, category: "pokemon", answers: ["Chikorita"], imageUrl: "chikorita.jpg" },
    { id: 275, category: "pokemon", answers: ["Mudkip"], imageUrl: "mudkip.jpg" },
    { id: 276, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto.jpg" },
    { id: 277, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_2.jpg" },
    { id: 278, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_3.jpg" },
    { id: 279, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_4.jpg" },
    { id: 280, category: "pokemon", answers: ["Heracross"], imageUrl: "heracross.jpg" },
    { id: 281, category: "characters", answers: ["Cell. Jr"], imageUrl: "cell_jr.jpg" },
    { id: 282, category: "characters", answers: ["Mestre Karin"], imageUrl: "mestre_karin.jpg" },
    { id: 283, category: "characters", answers: ["Yamcha"], imageUrl: "yamcha.jpg" },
    { id: 284, category: "characters", answers: ["Tenshinhan"], imageUrl: "tenshinhan.jpg" },
    { id: 285, category: "characters", answers: ["Chaos"], imageUrl: "chaos.jpg" },
    { id: 286, category: "characters", answers: ["Knuckles"], imageUrl: "knuckles.jpg" },
    { id: 287, category: "characters", answers: ["Tails"], imageUrl: "tails.jpg" },
    { id: 288, category: "characters", answers: ["Amy Rose"], imageUrl: "amy_rose.jpg" },
    { id: 289, category: "characters", answers: ["Big the Cat"], imageUrl: "big_the_cat.jpg" },
    { id: 290, category: "characters", answers: ["Metal Sonic"], imageUrl: "metal_sonic.jpg" },
    { id: 291, category: "characters", answers: ["Zamasu"], imageUrl: "zamasu.jpg" },
    { id: 292, category: "characters", answers: ["Hitto"], imageUrl: "hitto.jpg" },
    { id: 293, category: "characters", answers: ["Fusão Zamasu"], imageUrl: "fusao_zamasu.jpg" },
    { id: 294, category: "characters", answers: ["Kid Buu"], imageUrl: "kid_buu.jpg" },
    { id: 295, category: "characters", answers: ["Majin Buu"], imageUrl: "majin_buu.jpg" },
    { id: 296, category: "characters", answers: ["Super Buu"], imageUrl: "super_buu.jpg" },
    { id: 297, category: "characters", answers: ["Ultra Buu"], imageUrl: "ultra_buu.jpg" },
    { id: 298, category: "characters", answers: ["Super Buuhan"], imageUrl: "super_buuhan.jpg" },
    { id: 299, category: "characters", answers: ["Super Buutenks"], imageUrl: "super_buutenks.jpg" },
    { id: 300, category: "characters", answers: ["Super Buucolo"], imageUrl: "super_buucolo.jpg" },
    { id: 301, category: "characters", answers: ["Vegetto"], imageUrl: "vegetto.jpg" },
    { id: 302, category: "characters", answers: ["Gogeta"], imageUrl: "gogeta.jpg" },
    { id: 303, category: "characters", answers: ["Broly"], imageUrl: "broly.jpg" },
    { id: 304, category: "characters", answers: ["Broly"], imageUrl: "broly_dbs.jpg" },
    { id: 305, category: "anime", answers: ["Dragon Ball"], imageUrl: "dragon_ball.jpg" },
    { id: 306, category: "anime", answers: ["Dragon Ball Super"], imageUrl: "dragon_ball_super.jpg" },
    { id: 307, category: "anime", answers: ["Dragon Ball GT"], imageUrl: "dragon_ball_gt.jpg" },
    { id: 308, category: "anime", answers: ["Naruto Shippuden"], imageUrl: "naruto_shippuden.jpg" },
    { id: 309, category: "anime", answers: ["Boruto"], imageUrl: "boruto.jpg" },
    { id: 310, category: "anime", answers: ["One Piece"], imageUrl: "one_piece_2.jpg" },
    { id: 311, category: "characters", answers: ["Ace"], imageUrl: "ace.jpg" },
    { id: 312, category: "characters", answers: ["Sabo"], imageUrl: "sabo.jpg" },
    { id: 313, category: "characters", answers: ["Shanks"], imageUrl: "shanks.jpg" },
    { id: 314, category: "characters", answers: ["Tashigi"], imageUrl: "tashigi.jpg" },
    { id: 315, category: "characters", answers: ["Smoker"], imageUrl: "smoker.jpg" },
    { id: 316, category: "characters", answers: ["Kizaru"], imageUrl: "kizaru.jpg" },
    { id: 317, category: "characters", answers: ["Luffy"], imageUrl: "luffy.jpg" },
    { id: 318, category: "characters", answers: ["Luffy Pesadelo"], imageUrl: "luffy_pesadelo.jpg" },
    { id: 319, category: "characters", answers: ["Zoro"], imageUrl: "zoro.jpg" },
    { id: 320, category: "characters", answers: ["Nami"], imageUrl: "nami.jpg" },
    { id: 321, category: "characters", answers: ["Usopp"], imageUrl: "usopp.jpg" },
    { id: 322, category: "characters", answers: ["Sanji"], imageUrl: "sanji.jpg" },
    { id: 323, category: "characters", answers: ["Chopper"], imageUrl: "chopper.jpg" },
    { id: 324, category: "characters", answers: ["Sogeking"], imageUrl: "sogeking.jpg" },
    { id: 325, category: "characters", answers: ["Luke Skywalker"], imageUrl: "luke_skywalker.jpg" },
    { id: 326, category: "characters", answers: ["Darth Vader"], imageUrl: "darth_vader.jpg" },
    { id: 327, category: "characters", answers: ["Yoda"], imageUrl: "yoda.jpg" },
    { id: 328, category: "characters", answers: ["Obi-Wan Kenobi"], imageUrl: "obi_wan_kenobi.jpg" },
    { id: 329, category: "characters", answers: ["Han Solo"], imageUrl: "han_solo.jpg" },
    { id: 330, category: "characters", answers: ["Chewbacca"], imageUrl: "chewbacca.jpg" },
    { id: 331, category: "characters", answers: ["R2-D2"], imageUrl: "r2_d2.jpg" },
    { id: 332, category: "characters", answers: ["C-3PO"], imageUrl: "c_3po.jpg" },
    { id: 333, category: "characters", answers: ["Boba Fett"], imageUrl: "boba_fett.jpg" },
    { id: 334, category: "characters", answers: ["Mandaloriano"], imageUrl: "mandaloriano.jpg" },
    { id: 335, category: "characters", answers: ["Gaara"], imageUrl: "gaara.jpg" },
    { id: 336, category: "characters", answers: ["Sasuke Uchiha"], imageUrl: "sasuke_uchiha.jpg" },
    { id: 337, category: "characters", answers: ["Itachi Uchiha"], imageUrl: "itachi_uchiha.jpg" },
    { id: 338, category: "characters", answers: ["Naruto"], imageUrl: "naruto_uzumaki.jpg" },
    { id: 339, category: "characters", answers: ["Sakura"], imageUrl: "sakura_haruno.jpg" },
    { id: 340, category: "characters", answers: ["Kakashi"], imageUrl: "kakashi_hatake.jpg" },
    { id: 341, category: "characters", answers: ["Rasa"], imageUrl: "rasa.jpg" },
    { id: 342, category: "characters", answers: ["Tobirama"], imageUrl: "tobirama.jpg" },
    { id: 343, category: "characters", answers: ["Minato"], imageUrl: "minato.jpg" },
    { id: 344, category: "characters", answers: ["Jiraiya"], imageUrl: "jiraiya.jpg" },
    { id: 345, category: "characters", answers: ["Orochimaru"], imageUrl: "orochimaru.jpg" },
    { id: 346, category: "characters", answers: ["Orochimaru"], imageUrl: "orochimaru_2.jpg" },
    { id: 347, category: "characters", answers: ["Madara Uchiha"], imageUrl: "madara_uchiha.jpg" },
    { id: 348, category: "characters", answers: ["Madara Uchiha"], imageUrl: "madara_uchiha_2.jpg" },
    { id: 349, category: "characters", answers: ["Obito Uchiha"], imageUrl: "obito_uchiha.jpg" },
    { id: 350, category: "characters", answers: ["Obito Uchiha"], imageUrl: "obito_uchiha_2.jpg" },
    { id: 351, category: "characters", answers: ["Tobi"], imageUrl: "tobi.jpg" },
    { id: 352, category: "pokemon", answers: ["Greninja"], imageUrl: "greninja.jpg" },
    { id: 353, category: "pokemon", answers: ["Ash Greninja"], imageUrl: "ash_greninja.jpg" },
    { id: 354, category: "pokemon", answers: ["Infernape"], imageUrl: "infernape.jpg" },
    { id: 355, category: "pokemon", answers: ["Empoleon"], imageUrl: "empoleon.jpg" },
    { id: 356, category: "pokemon", answers: ["Torterra"], imageUrl: "torterra.jpg" },
    { id: 357, category: "pokemon", answers: ["Lucario"], imageUrl: "lucario.jpg" },
    { id: 358, category: "pokemon", answers: ["Cresselia"], imageUrl: "cresselia.jpg" },
    { id: 359, category: "characters", answers: ["Sage"], imageUrl: "sage.jpg" },
    { id: 360, category: "characters", answers: ["Jett"], imageUrl: "jett.jpg" },
    { id: 361, category: "characters", answers: ["Phoenix"], imageUrl: "phoenix.jpg" },
    { id: 362, category: "characters", answers: ["Sova"], imageUrl: "sova.jpg" },
    { id: 363, category: "characters", answers: ["Reyna"], imageUrl: "reyna.jpg" },
    { id: 364, category: "characters", answers: ["Cypher"], imageUrl: "cypher.jpg" },
    { id: 365, category: "characters", answers: ["Eren"], imageUrl: "eren.jpg" },
    { id: 366, category: "characters", answers: ["Mikasa"], imageUrl: "mikasa.jpg" },
    { id: 367, category: "characters", answers: ["Armin"], imageUrl: "armin.jpg" },
    { id: 368, category: "characters", answers: ["Levi"], imageUrl: "levi.jpg" },
    { id: 369, category: "characters", answers: ["Erwin"], imageUrl: "erwin.jpg" },
    { id: 370, category: "characters", answers: ["Hange"], imageUrl: "hange.jpg" },
    { id: 371, category: "characters", answers: ["Edward Elric"], imageUrl: "edward_elric.jpg" },
    { id: 372, category: "characters", answers: ["Alphonse Elric"], imageUrl: "alphonse_elric.jpg" },
    { id: 373, category: "characters", answers: ["Roy Mustang"], imageUrl: "roy_mustang.jpg" },
    { id: 374, category: "characters", answers: ["Scar"], imageUrl: "scar.jpg" },
    { id: 375, category: "characters", answers: ["Luxúria"], imageUrl: "luxuria.jpg" },
    { id: 376, category: "characters", answers: ["Inveja"], imageUrl: "inveja.jpg" },
    { id: 377, category: "characters", answers: ["Gon"], imageUrl: "gon.jpg" },
    { id: 378, category: "characters", answers: ["Killua"], imageUrl: "killua.jpg" },
    { id: 379, category: "characters", answers: ["Kurapika"], imageUrl: "kurapika.jpg" },
    { id: 380, category: "characters", answers: ["L"], imageUrl: "l.jpg" },
    { id: 381, category: "characters", answers: ["Light Yagami"], imageUrl: "light_yagami.jpg" },
    { id: 382, category: "characters", answers: ["Near"], imageUrl: "near.jpg" },
    { id: 383, category: "characters", answers: ["Misa Amane"], imageUrl: "misa_amane.jpg" },
    { id: 384, category: "characters", answers: ["Mello"], imageUrl: "mello.jpg" },
    { id: 385, category: "games", answers: ["Rocket League"], imageUrl: "rocket_league.jpg" },
    { id: 386, category: "games", answers: ["Among Us"], imageUrl: "among_us.jpg" },
    { id: 387, category: "games", answers: ["Fall Guys"], imageUrl: "fall_guys.jpg" },
    { id: 388, category: "games", answers: ["The Sims"], imageUrl: "the_sims.jpg" },
    { id: 389, category: "games", answers: ["The Sims 2"], imageUrl: "the_sims_2.jpg" },
    { id: 390, category: "games", answers: ["The Sims 3"], imageUrl: "the_sims_3.jpg" },
    { id: 391, category: "games", answers: ["The Sims 4"], imageUrl: "the_sims_4.jpg" },
    { id: 392, category: "games", answers: ["Spore"], imageUrl: "spore.jpg" },
    { id: 393, category: "games", answers: ["2XKO"], imageUrl: "2xko.jpg" },
    { id: 394, category: "games", answers: ["GTA San Andreas"], imageUrl: "gta_san_andreas.jpg" },
    { id: 395, category: "games", answers: ["GTA Vice City"], imageUrl: "gta_vice_city.jpg" },
    { id: 396, category: "games", answers: ["Red Dead Redemption"], imageUrl: "red_dead_redemption.jpg" },
    { id: 397, category: "games", answers: ["Mortal Kombat 3"], imageUrl: "mortal_kombat_3.jpg" },
    { id: 398, category: "games", answers: ["Mortal Kombat 11"], imageUrl: "mortal_kombat_11.jpg" },
    { id: 399, category: "games", answers: ["Street Fighter 2"], imageUrl: "street_fighter_2.jpg" },
    { id: 400, category: "games", answers: ["Street Fighter 6"], imageUrl: "street_fighter_6.jpg" }
];