import { Question } from "../types/Question";

export const questionList: Question[] = [
    //FÁCEIS
    { id: 1, category: "anime", answer: "Naruto", imageUrl: "naruto.jpg" },
    { id: 2, category: "anime", answer: "One Piece", imageUrl: "one_piece.jpg" },
    { id: 3, category: "anime", answer: "Attack on Titan", imageUrl: "attack_on_titan.jpg" },
    { id: 4, category: "anime", answer: "Fullmetal Alchemist", imageUrl: "fullmetal_alchemist.jpg" },
    { id: 5, category: "anime", answer: "Death Note", imageUrl: "death_note.jpg" },
    { id: 6, category: "anime", answer: "Dragon Ball Z", imageUrl: "dragon_ball_z.jpg" },
    { id: 7, category: "anime", answer: "My Hero Academia", imageUrl: "my_hero_academia.jpg" },
    { id: 8, category: "anime", answer: "Demon Slayer", imageUrl: "demon_slayer.jpg" },
    { id: 9, category: "anime", answer: "Tokyo Ghoul", imageUrl: "tokyo_ghoul.jpg" },
    { id: 10, category: "anime", answer: "Sword Art Online", imageUrl: "sword_art_online.jpg" },
    { id: 11, category: "anime", answer: "Bleach", imageUrl: "bleach.jpg" },
    { id: 12, category: "anime", answer: "Fairy Tail", imageUrl: "fairy_tail.jpg" },
    { id: 13, category: "anime", answer: "Cowboy Bebop", imageUrl: "cowboy_bepop.jpg" },
    { id: 14, category: "anime", answer: "Neon Genesis Evangelion", imageUrl: "neon_genesis_evangelion.jpg" },
    { id: 15, category: "anime", answer: "JoJo's Bizarre Adventure", imageUrl: "jojo.jpg" },
    { id: 16, category: "anime", answer: "Hunter x Hunter", imageUrl: "hunter_x_hunter.jpg" },
    { id: 17, category: "anime", answer: "Black Clover", imageUrl: "black_clover.jpg" },
    { id: 18, category: "anime", answer: "Gintama", imageUrl: "gintama.jpg" },
    { id: 19, category: "anime", answer: "Mob Psycho 100", imageUrl: "mob_psycho_100.jpg" },
    { id: 20, category: "anime", answer: "The Seven Deadly Sins", imageUrl: "seven_deadly_sins.jpg" },
    { id: 21, category: "pokemon", answer: "Bulbasaur", imageUrl: "bulbasaur.jpg" },
    { id: 22, category: "pokemon", answer: "Ivysaur", imageUrl: "ivysaur.jpg" },
    { id: 23, category: "pokemon", answer: "Venusaur", imageUrl: "venusaur.jpg" },
    { id: 24, category: "pokemon", answer: "Charmander", imageUrl: "charmander.jpg" },
    { id: 25, category: "pokemon", answer: "Charmeleon", imageUrl: "charmeleon.jpg" },
    { id: 26, category: "pokemon", answer: "Charizard", imageUrl: "charizard.jpg" },
    { id: 27, category: "pokemon", answer: "Squirtle", imageUrl: "squirtle.jpg" },
    { id: 28, category: "pokemon", answer: "Wartortle", imageUrl: "wartortle.jpg" },
    { id: 29, category: "pokemon", answer: "Blastoise", imageUrl: "blastoise.jpg" },
    { id: 30, category: "pokemon", answer: "Pikachu", imageUrl: "pikachu.jpg" },
    { id: 31, category: "pokemon", answer: "Raichu", imageUrl: "raichu.jpg" },
    { id: 32, category: "pokemon", answer: "Jigglypuff", imageUrl: "jigglypuff.jpg" },
    { id: 33, category: "pokemon", answer: "Meowth", imageUrl: "meowth.jpg" },
    { id: 34, category: "pokemon", answer: "Psyduck", imageUrl: "psyduck.jpg" },
    { id: 35, category: "pokemon", answer: "Machop", imageUrl: "machop.jpg" },
    { id: 36, category: "pokemon", answer: "Geodude", imageUrl: "geodude.jpg" },
    { id: 37, category: "pokemon", answer: "Eevee", imageUrl: "eevee.jpg" },
    { id: 38, category: "pokemon", answer: "Snorlax", imageUrl: "snorlax.jpg" },
    { id: 39, category: "pokemon", answer: "Mewtwo", imageUrl: "mewtwo.jpg" },
    { id: 40, category: "pokemon", answer: "Magikarp", imageUrl: "magikarp.jpg" },
    { id: 41, category: "characters", answer: "Mario", imageUrl: "mario.jpg" },
    { id: 42, category: "characters", answer: "Luigi", imageUrl: "luigi.jpg" },
    { id: 43, category: "characters", answer: "Shadow", imageUrl: "shadow.jpg" },
    { id: 44, category: "characters", answer: "Link", imageUrl: "link.jpg" },
    { id: 45, category: "characters", answer: "Ash Ketchum", imageUrl: "ash_ketchum.jpg" },
    { id: 46, category: "characters", answer: "Killer Bee", imageUrl: "killer_bee.jpg" },
    { id: 47, category: "characters", answer: "Goku Black", imageUrl: "goku_black.jpg" },
    { id: 48, category: "characters", answer: "Sailor Moon", imageUrl: "sailor_moon.jpg" },
    { id: 49, category: "characters", answer: "Batman", imageUrl: "batman.jpg" },
    { id: 50, category: "characters", answer: "Homem de Ferro", imageUrl: "homem_de_ferro.jpg" },
    { id: 51, category: "characters", answer: "Capitão América", imageUrl: "capitao_america.jpg" },
    { id: 52, category: "characters", answer: "Thor", imageUrl: "thor.jpg" },
    { id: 53, category: "characters", answer: "Lara Croft", imageUrl: "lara_croft.jpg" },
    { id: 54, category: "characters", answer: "Kratos", imageUrl: "kratos.jpg" },
    { id: 55, category: "characters", answer: "Master Chief", imageUrl: "master_chief.jpg" },
    { id: 56, category: "characters", answer: "Solid Snake", imageUrl: "solid_snake.jpg" },
    { id: 57, category: "characters", answer: "Yoshi", imageUrl: "yoshi.jpg" },
    { id: 58, category: "characters", answer: "Donkey Kong", imageUrl: "donkey_kong.jpg" },
    { id: 59, category: "characters", answer: "Kirby", imageUrl: "kirby.jpg" },
    { id: 60, category: "characters", answer: "Rock Lee", imageUrl: "rock_lee.jpg" },
    { id: 61, category: "movies", answer: "Inception", imageUrl: "inception.jpg" },
    { id: 62, category: "movies", answer: "Interstelar", imageUrl: "interstelar.jpg" },
    { id: 63, category: "movies", answer: "De Volta Para o Futuro", imageUrl: "de_volta_para_o_futuro.jpg" },
    { id: 64, category: "movies", answer: "Forrest Gump", imageUrl: "forrest_gump.jpg" },
    { id: 66, category: "movies", answer: "Pulp Fiction", imageUrl: "pulp_fiction.jpg" },
    { id: 67, category: "movies", answer: "Star Wars", imageUrl: "star_wars.jpg" },
    { id: 68, category: "movies", answer: "Matrix", imageUrl: "matrix.jpg" },
    { id: 69, category: "movies", answer: "Titanic", imageUrl: "titanic.jpg" },
    { id: 70, category: "movies", answer: "Gladiador", imageUrl: "gladiador.jpg" },
    { id: 71, category: "movies", answer: "Jurassic Park", imageUrl: "jurassic_park.jpg" },
    { id: 72, category: "movies", answer: "Avatar", imageUrl: "avatar.jpg" },
    { id: 73, category: "movies", answer: "O Rei Leão", imageUrl: "o_rei_leao.jpg" },
    { id: 74, category: "movies", answer: "Homem-Aranha 3", imageUrl: "homem_aranha_3.jpg" },
    { id: 75, category: "movies", answer: "Coringa", imageUrl: "coringa.jpg" },
    { id: 76, category: "movies", answer: "Os Vingadores", imageUrl: "os_vingadores.jpg" },
    { id: 77, category: "movies", answer: "Harry Potter", imageUrl: "harry_potter.jpg" },
    { id: 78, category: "movies", answer: "Brilho Eterno de uma Mente Sem Lembranças", imageUrl: "brilho_eterno.jpg" },
    { id: 79, category: "movies", answer: "Cidadão Kane", imageUrl: "cidadao_kane.jpg" },
    { id: 80, category: "movies", answer: "O Grande Lebowski", imageUrl: "o_grande_lebowski.jpg" },
    { id: 81, category: "games", answer: "The Witcher 3", imageUrl: "the_witcher_3.jpg" },
    { id: 82, category: "games", answer: "Red Dead Redemption 2", imageUrl: "red_dead_redemption_2.jpg" },
    { id: 83, category: "games", answer: "The Last of Us", imageUrl: "the_last_of_us.jpg" },
    { id: 84, category: "games", answer: "God of War", imageUrl: "god_of_war.jpg" },
    { id: 85, category: "games", answer: "Minecraft", imageUrl: "minecraft.jpg" },
    { id: 86, category: "games", answer: "Fortnite", imageUrl: "fortnite.jpg" },
    { id: 87, category: "games", answer: "League of Legends", imageUrl: "league_of_legends.jpg" },
    { id: 88, category: "games", answer: "Overwatch", imageUrl: "overwatch.jpg" },
    { id: 89, category: "games", answer: "Cyberpunk 2077", imageUrl: "cyberpunk_2077.jpg" },
    { id: 90, category: "games", answer: "Elden Ring", imageUrl: "elden_ring.jpg" },
    { id: 91, category: "games", answer: "Hollow Knight", imageUrl: "hollow_knight.jpg" },
    { id: 92, category: "games", answer: "Dark Souls 2", imageUrl: "dark_souls_2.jpg" },
    { id: 93, category: "games", answer: "Super Mario Odyssey", imageUrl: "super_mario_odyssey.jpg" },
    { id: 94, category: "games", answer: "Pokémon Yellow", imageUrl: "pokemon_yellow.jpg" },
    { id: 95, category: "games", answer: "Doom Eternal", imageUrl: "doom_eternal.jpg" },
    { id: 96, category: "games", answer: "Resident Evil 7", imageUrl: "resident_evil_7.jpg" },
    { id: 97, category: "games", answer: "Final Fantasy 7", imageUrl: "final_fantasy_7.jpg" },
    { id: 98, category: "games", answer: "Terraria", imageUrl: "terraria.jpg" },
    { id: 99, category: "games", answer: "Sonic 2", imageUrl: "sonic_2.jpg" },
    { id: 100, category: "games", answer: "Cuphead", imageUrl: "cuphead.jpg" },
    { id: 101, category: "music", answer: "Queen", imageUrl: "queen.jpg" },
    { id: 102, category: "music", answer: "The Beatles", imageUrl: "the_beatles.jpg" },
    { id: 103, category: "music", answer: "Michael Jackson", imageUrl: "michael_jackson.jpg" },
    { id: 104, category: "music", answer: "Madonna", imageUrl: "madonna.jpg" },
    { id: 105, category: "music", answer: "Elvis Presley", imageUrl: "elvis_presley.jpg" },
    { id: 106, category: "music", answer: "Beyoncé", imageUrl: "beyonce.jpg" },
    { id: 107, category: "music", answer: "Taylor Swift", imageUrl: "taylor_swift.jpg" },
    { id: 108, category: "music", answer: "Adele", imageUrl: "adele.jpg" },
    { id: 109, category: "music", answer: "Drake", imageUrl: "drake.jpg" },
    { id: 110, category: "music", answer: "Player Tauz", imageUrl: "player_tauz.jpg" },
    { id: 111, category: "music", answer: "Katy Perry", imageUrl: "katy_perry.jpg" },
    { id: 112, category: "music", answer: "Bruno Mars", imageUrl: "bruno_mars.jpg" },
    { id: 113, category: "music", answer: "Rihanna", imageUrl: "rihanna.jpg" },
    { id: 114, category: "music", answer: "Eminem", imageUrl: "eminem.jpg" },
    { id: 115, category: "music", answer: "Billie Eilish", imageUrl: "billie_eilish.jpg" },
    { id: 116, category: "music", answer: "Coldplay", imageUrl: "coldplay.jpg" },
    { id: 117, category: "music", answer: "Anitta", imageUrl: "anitta.jpg" },
    { id: 118, category: "music", answer: "Linkin Park", imageUrl: "linkin_park.jpg" },
    { id: 119, category: "music", answer: "Nirvana", imageUrl: "nirvana.jpg" },
    { id: 120, category: "music", answer: "Luan Santana", imageUrl: "luan_santana.jpg" },
    { id: 121, category: "tvShows", answer: "Breaking Bad", imageUrl: "breaking_bad.jpg" },
    { id: 122, category: "tvShows", answer: "Game of Thrones", imageUrl: "game_of_thrones.jpg" },
    { id: 123, category: "tvShows", answer: "Stranger Things", imageUrl: "stranger_things.jpg" },
    { id: 124, category: "tvShows", answer: "The Crown", imageUrl: "the_crown.jpg" },
    { id: 125, category: "tvShows", answer: "The Mandalorian", imageUrl: "the_mandalorian.jpg" },
    { id: 126, category: "tvShows", answer: "Friends", imageUrl: "friends.jpg" },
    { id: 127, category: "tvShows", answer: "The Office", imageUrl: "the_office.jpg" },
    { id: 128, category: "tvShows", answer: "Sherlock", imageUrl: "sherlock.jpg" },
    { id: 129, category: "tvShows", answer: "Westworld", imageUrl: "westworld.jpg" },
    { id: 130, category: "tvShows", answer: "Peaky Blinders", imageUrl: "peaky_blinders.jpg" },
    { id: 131, category: "tvShows", answer: "The Witcher", imageUrl: "the_witcher.jpg" },
    { id: 132, category: "tvShows", answer: "House of Cards", imageUrl: "house_of_cards.jpg" },
    { id: 133, category: "tvShows", answer: "Better Call Saul", imageUrl: "better_call_saul.jpg" },
    { id: 134, category: "tvShows", answer: "Black Mirror", imageUrl: "black_mirror.jpg" },
    { id: 135, category: "tvShows", answer: "Narcos", imageUrl: "narcos.jpg" },
    { id: 136, category: "tvShows", answer: "The Boys", imageUrl: "the_boys.jpg" },
    { id: 137, category: "tvShows", answer: "Loki", imageUrl: "loki.jpg" },
    { id: 138, category: "tvShows", answer: "WandaVision", imageUrl: "wandavision.jpg" },
    { id: 139, category: "tvShows", answer: "Lupin", imageUrl: "lupin.jpg" },
    { id: 140, category: "tvShows", answer: "Round 6", imageUrl: "round_6.jpg" },
    { id: 141, category: "cartoons", answer: "Bob Esponja", imageUrl: "bob_esponja.jpg" },
    { id: 142, category: "cartoons", answer: "Pica-Pau", imageUrl: "pica_pau.jpg" },
    { id: 143, category: "cartoons", answer: "Tom e Jerry", imageUrl: "tom_e_jerry.jpg" },
    { id: 144, category: "cartoons", answer: "O Incrível Mundo de Gumball", imageUrl: "o_incrivel_mundo_de_gumball.jpg" },
    { id: 145, category: "cartoons", answer: "Hora de Aventura", imageUrl: "hora_de_aventura.jpg" },
    { id: 146, category: "cartoons", answer: "Os Padrinhos Mágicos", imageUrl: "os_padrinhos_magicos.jpg" },
    { id: 147, category: "cartoons", answer: "Os Simpsons", imageUrl: "os_simpsons.jpg" },
    { id: 148, category: "cartoons", answer: "Futurama", imageUrl: "futurama.jpg" },
    { id: 149, category: "cartoons", answer: "Rick e Morty", imageUrl: "rick_e_morty.jpg" },
    { id: 150, category: "cartoons", answer: "Ursinho Pooh", imageUrl: "ursinho_pooh.jpg" },
    { id: 151, category: "cartoons", answer: "Apenas um Show", imageUrl: "apenas_um_show.jpg" },
    { id: 152, category: "cartoons", answer: "Sonic Satam", imageUrl: "sonic_satam.jpg" },
    { id: 153, category: "cartoons", answer: "As Meninas Superpoderosas", imageUrl: "as_meninas_superpoderosas.jpg" },
    { id: 154, category: "cartoons", answer: "Ben 10", imageUrl: "ben_10.jpg" },
    { id: 155, category: "cartoons", answer: "Phineas e Ferb", imageUrl: "phineas_e_ferb.jpg" },
    { id: 156, category: "cartoons", answer: "Slugterrâneo", imageUrl: "slugterraneo.jpg" },
    { id: 157, category: "cartoons", answer: "Kid vs Cat", imageUrl: "kid_vs_cat.jpg" },
    { id: 158, category: "cartoons", answer: "Liga da Justiça", imageUrl: "liga_da_justica.jpg" },
    { id: 159, category: "cartoons", answer: "Super Choque", imageUrl: "super_choque.jpg" },
    { id: 160, category: "cartoons", answer: "Peixonauta", imageUrl: "peixonauta.jpg" },
    { id: 161, category: "logo", answer: "Nike", imageUrl: "nike.jpg" },
    { id: 162, category: "logo", answer: "Adidas", imageUrl: "adidas.jpg" },
    { id: 163, category: "logo", answer: "Apple", imageUrl: "apple.jpg" },
    { id: 164, category: "logo", answer: "NVIDIA", imageUrl: "nvidia.jpg" },
    { id: 165, category: "logo", answer: "Starbucks", imageUrl: "starbucks.jpg" },
    { id: 166, category: "logo", answer: "Pepsi", imageUrl: "pepsi.jpg" },
    { id: 167, category: "logo", answer: "Kabum", imageUrl: "kabum.jpg" },
    { id: 168, category: "logo", answer: "AMD", imageUrl: "amd.jpg" },
    { id: 169, category: "logo", answer: "Android", imageUrl: "android.jpg" },
    { id: 170, category: "logo", answer: "Microsoft", imageUrl: "microsoft.jpg" },
    { id: 171, category: "logo", answer: "Facebook", imageUrl: "facebook.jpg" },
    { id: 172, category: "logo", answer: "Twitter", imageUrl: "twitter.jpg" },
    { id: 173, category: "logo", answer: "YouTube Music", imageUrl: "youtube_music.jpg" },
    { id: 174, category: "logo", answer: "Amazon", imageUrl: "amazon.jpg" },
    { id: 175, category: "logo", answer: "Samsung", imageUrl: "samsung.jpg" },
    { id: 176, category: "logo", answer: "Toyota", imageUrl: "toyota.jpg" },
    { id: 177, category: "logo", answer: "BMW", imageUrl: "bmw.jpg" },
    { id: 178, category: "logo", answer: "Volkswagen", imageUrl: "volkswagen.jpg" },
    { id: 179, category: "logo", answer: "Audi", imageUrl: "audi.jpg" },
    { id: 180, category: "logo", answer: "Honda", imageUrl: "honda.jpg" },
    { id: 181, category: "flag", answer: "Brasil", imageUrl: "brasil.jpg" },
    { id: 182, category: "flag", answer: "Estados Unidos", imageUrl: "estados_unidos.jpg" },
    { id: 183, category: "flag", answer: "Japão", imageUrl: "japao.jpg" },
    { id: 184, category: "flag", answer: "Alemanha", imageUrl: "alemanha.jpg" },
    { id: 185, category: "flag", answer: "Egito", imageUrl: "egito.jpg" },
    { id: 186, category: "flag", answer: "Itália", imageUrl: "italia.jpg" },
    { id: 187, category: "flag", answer: "Reino Unido", imageUrl: "reino_unido.jpg" },
    { id: 188, category: "flag", answer: "Canadá", imageUrl: "canada.jpg" },
    { id: 189, category: "flag", answer: "China", imageUrl: "china.jpg" },
    { id: 190, category: "flag", answer: "Índia", imageUrl: "india.jpg" },
    { id: 191, category: "flag", answer: "Suriname", imageUrl: "suriname.jpg" },
    { id: 192, category: "flag", answer: "Austrália", imageUrl: "australia.jpg" },
    { id: 193, category: "flag", answer: "México", imageUrl: "mexico.jpg" },
    { id: 194, category: "flag", answer: "Argentina", imageUrl: "argentina.jpg" },
    { id: 195, category: "flag", answer: "África do Sul", imageUrl: "africa_do_sul.jpg" },
    { id: 196, category: "flag", answer: "Coreia do Norte", imageUrl: "coreia_do_norte.jpg" },
    { id: 197, category: "flag", answer: "Espanha", imageUrl: "espanha.jpg" },
    { id: 198, category: "flag", answer: "Suécia", imageUrl: "suecia.jpg" },
    { id: 199, category: "flag", answer: "Noruega", imageUrl: "noruega.jpg" },
    { id: 200, category: "flag", answer: "Suiça", imageUrl: "suica.jpg" },
    { id: 201, category: "soccer", answer: "Barcelona", imageUrl: "barcelona.jpg" },
    { id: 202, category: "soccer", answer: "Real Madrid", imageUrl: "real_madrid.jpg" },
    { id: 203, category: "soccer", answer: "Manchester United", imageUrl: "manchester_united.jpg" },
    { id: 204, category: "soccer", answer: "Liverpool", imageUrl: "liverpool.jpg" },
    { id: 205, category: "soccer", answer: "Juventus", imageUrl: "juventus.jpg" },
    { id: 206, category: "soccer", answer: "Fluminense", imageUrl: "fluminense.jpg" },
    { id: 207, category: "soccer", answer: "Corinthians", imageUrl: "corinthians.jpg" },
    { id: 208, category: "soccer", answer: "LDU", imageUrl: "ldu.jpg" },
    { id: 209, category: "soccer", answer: "Santos", imageUrl: "santos.jpg" },
    { id: 210, category: "soccer", answer: "Inter de Milão", imageUrl: "inter_de_milao.jpg" },
    { id: 211, category: "soccer", answer: "Boca Júniors", imageUrl: "boca_juniors.jpg" },
    { id: 212, category: "soccer", answer: "Chelsea", imageUrl: "chelsea.jpg" },
    { id: 213, category: "soccer", answer: "Arsenal", imageUrl: "arsenal.jpg" },
    { id: 214, category: "soccer", answer: "River Plate", imageUrl: "river_plate.jpg" },
    { id: 215, category: "soccer", answer: "Independiente", imageUrl: "independiente.jpg" },
    { id: 216, category: "soccer", answer: "San Lorenzo", imageUrl: "san_lorenzo.jpg" },
    { id: 217, category: "soccer", answer: "Grêmio", imageUrl: "gremio.jpg" },
    { id: 218, category: "soccer", answer: "Internacional", imageUrl: "internacional.jpg" },
    { id: 219, category: "soccer", answer: "Atlético Mineiro", imageUrl: "atletico_mineiro.jpg" },
    { id: 220, category: "soccer", answer: "Bayer Leverkusen", imageUrl: "bayer_leverkusen.jpg" },
    { id: 221, category: "fruits", answer: "Maçã", imageUrl: "maca.jpg" },
    { id: 222, category: "fruits", answer: "Banana", imageUrl: "banana.jpg" },
    { id: 223, category: "fruits", answer: "Laranja", imageUrl: "laranja.jpg" },
    { id: 224, category: "fruits", answer: "Morango", imageUrl: "morango.jpg" },
    { id: 225, category: "fruits", answer: "Abacaxi", imageUrl: "abacaxi.jpg" },
    { id: 226, category: "fruits", answer: "Uva", imageUrl: "uva.jpg" },
    { id: 227, category: "fruits", answer: "Melancia", imageUrl: "melancia.jpg" },
    { id: 228, category: "fruits", answer: "Pera", imageUrl: "pera.jpg" },
    { id: 229, category: "fruits", answer: "Tangerina", imageUrl: "tangerina.jpg" },
    { id: 230, category: "fruits", answer: "Framboesa", imageUrl: "framboesa.jpg" },
    { id: 231, category: "animals", answer: "Onça", imageUrl: "onca.jpg" },
    { id: 232, category: "animals", answer: "Urso Polar", imageUrl: "urso_polar.jpg" },
    { id: 233, category: "animals", answer: "Coala", imageUrl: "coala.jpg" },
    { id: 234, category: "animals", answer: "Hipopótamo", imageUrl: "hipopotamo.jpg" },
    { id: 235, category: "animals", answer: "Rinoceronte", imageUrl: "rinoceronte.jpg" },
    { id: 236, category: "animals", answer: "Chita", imageUrl: "chita.jpg" },
    { id: 237, category: "animals", answer: "Boto", imageUrl: "boto.jpg" },
    { id: 238, category: "animals", answer: "Águia", imageUrl: "aguia.jpg" },
    { id: 239, category: "animals", answer: "Falcão", imageUrl: "falcao.jpg" },
    { id: 240, category: "animals", answer: "Crocodilo", imageUrl: "crocodilo.jpg" },
    { id: 241, category: "animals", answer: "Golfinho", imageUrl: "golfinho.jpg" },
    { id: 242, category: "animals", answer: "Jacaré", imageUrl: "jacare.jpg" },
    { id: 243, category: "characters", answer: "Pepsiman", imageUrl: "pepsiman.jpg" },
    { id: 244, category: "characters", answer: "Shisui Uchiha", imageUrl: "shisui_uchiha.jpg" },
    { id: 245, category: "characters", answer: "Jaco", imageUrl: "jaco.jpg" },
    { id: 246, category: "characters", answer: "Law", imageUrl: "law.jpg" },
    { id: 247, category: "characters", answer: "Gol D. Roger", imageUrl: "gol_d_roger.jpg" },
    { id: 248, category: "characters", answer: "Cooler", imageUrl: "cooler.jpg" },
    { id: 249, category: "characters", answer: "Kefla", imageUrl: "kefla.jpg" },
    { id: 250, category: "characters", answer: "Nail", imageUrl: "nail.jpg" },
    { id: 251, category: "characters", answer: "Boa Hancock", imageUrl: "boa_hancock.jpg" },
    { id: 252, category: "characters", answer: "Turles", imageUrl: "turles.jpg" },
    { id: 253, category: "characters", answer: "Zarbon", imageUrl: "zarbon.jpg" },
    { id: 254, category: "characters", answer: "Bardock", imageUrl: "bardock.jpg" },
    { id: 255, category: "games", answer: "Pepsiman", imageUrl: "pepsiman_ps1.jpg" },
    { id: 256, category: "games", answer: "Minecraft Legends", imageUrl: "minecraft_legends.jpg" },
    { id: 257, category: "games", answer: "Minecraft Dungeons", imageUrl: "minecraft_dungeons.jpg" },
    { id: 258, category: "games", answer: "Minecraft Story Mode", imageUrl: "minecraft_story_mode.jpg" },
    { id: 259, category: "games", answer: "Forza Horizon", imageUrl: "forza_horizon.jpg" },
    { id: 260, category: "games", answer: "Forza Horizon 3", imageUrl: "forza_horizon_3.jpg" },
    { id: 261, category: "games", answer: "Need For Speed Most Wanted", imageUrl: "need_for_speed_most_wanted.jpg" },
    { id: 262, category: "games", answer: "Need For Speed Underground 2", imageUrl: "need_for_speed_underground_2.jpg" },
    { id: 263, category: "games", answer: "Midnight Club 3", imageUrl: "midnight_club_3.jpg" },
    { id: 264, category: "games", answer: "Burnout Paradise", imageUrl: "burnout_paradise.jpg" },
    { id: 265, category: "games", answer: "Burnout Revenge", imageUrl: "burnout_revenge.jpg" },
    { id: 266, category: "pokemon", answer: "Celebi", imageUrl: "celebi.jpg" },
    { id: 267, category: "pokemon", answer: "Jirachi", imageUrl: "jirachi.jpg" },
    { id: 268, category: "pokemon", answer: "Deoxys", imageUrl: "deoxys.jpg" },
    { id: 269, category: "pokemon", answer: "Phione", imageUrl: "phione.jpg" },
    { id: 270, category: "pokemon", answer: "Manaphy", imageUrl: "manaphy.jpg" },
    { id: 271, category: "pokemon", answer: "Darkrai", imageUrl: "darkrai.jpg" },
    { id: 272, category: "pokemon", answer: "Totodile", imageUrl: "totodile.jpg" },
    { id: 273, category: "pokemon", answer: "Cyndaquil", imageUrl: "cyndaquil.jpg" },
    { id: 274, category: "pokemon", answer: "Chikorita", imageUrl: "chikorita.jpg" },
    { id: 275, category: "pokemon", answer: "Mudkip", imageUrl: "mudkip.jpg" },
    { id: 276, category: "pokemon", answer: "Ditto", imageUrl: "ditto.jpg" },
    { id: 277, category: "pokemon", answer: "Ditto", imageUrl: "ditto_2.jpg" },
    { id: 278, category: "pokemon", answer: "Ditto", imageUrl: "ditto_3.jpg" },
    { id: 279, category: "pokemon", answer: "Ditto", imageUrl: "ditto_4.jpg" },
    { id: 280, category: "pokemon", answer: "Heracross", imageUrl: "heracross.jpg" },
    { id: 281, category: "characters", answer: "Cell. Jr", imageUrl: "cell_jr.jpg" },
    { id: 282, category: "characters", answer: "Mestre Karin", imageUrl: "mestre_karin.jpg" },
    { id: 283, category: "characters", answer: "Yamcha", imageUrl: "yamcha.jpg" },
    { id: 284, category: "characters", answer: "Tenshinhan", imageUrl: "tenshinhan.jpg" },
    { id: 285, category: "characters", answer: "Chaos", imageUrl: "chaos.jpg" },
    { id: 286, category: "characters", answer: "Knuckles", imageUrl: "knuckles.jpg" },
    { id: 287, category: "characters", answer: "Tails", imageUrl: "tails.jpg" },
    { id: 288, category: "characters", answer: "Amy Rose", imageUrl: "amy_rose.jpg" },
    { id: 289, category: "characters", answer: "Big the Cat", imageUrl: "big_the_cat.jpg" },
    { id: 290, category: "characters", answer: "Metal Sonic", imageUrl: "metal_sonic.jpg" },
    { id: 291, category: "characters", answer: "Zamasu", imageUrl: "zamasu.jpg" },
    { id: 292, category: "characters", answer: "Hitto", imageUrl: "hitto.jpg" },
    { id: 293, category: "characters", answer: "Fusão Zamasu", imageUrl: "fusao_zamasu.jpg" },
    { id: 294, category: "characters", answer: "Kid Buu", imageUrl: "kid_buu.jpg" },
    { id: 295, category: "characters", answer: "Majin Buu", imageUrl: "majin_buu.jpg" },
    { id: 296, category: "characters", answer: "Super Buu", imageUrl: "super_buu.jpg" },
    { id: 297, category: "characters", answer: "Ultra Buu", imageUrl: "ultra_buu.jpg" },
    { id: 298, category: "characters", answer: "Super Buuhan", imageUrl: "super_buuhan.jpg" },
    { id: 299, category: "characters", answer: "Super Buutenks", imageUrl: "super_buutenks.jpg" },
    { id: 300, category: "characters", answer: "Super Buucolo", imageUrl: "super_buucolo.jpg"},
    { id: 301, category: "characters", answer: "Vegetto", imageUrl: "vegetto.jpg"},
    { id: 302, category: "characters", answer: "Gogeta", imageUrl: "gogeta.jpg"},
    { id: 303, category: "characters", answer: "Broly", imageUrl: "broly.jpg"},
    { id: 304, category: "characters", answer: "Broly", imageUrl: "broly_dbs.jpg"},
    { id: 305, category: "anime", answer: "Dragon Ball", imageUrl: "dragon_ball.jpg"},
    { id: 306, category: "anime", answer: "Dragon Ball Super", imageUrl: "dragon_ball_super.jpg"},
    { id: 307, category: "anime", answer: "Dragon Ball GT", imageUrl: "dragon_ball_gt.jpg"},
    { id: 308, category: "anime", answer: "Naruto Shippuden", imageUrl: "naruto_shippuden.jpg" },
    { id: 309, category: "anime", answer: "Boruto", imageUrl: "boruto.jpg" },
    { id: 310, category: "anime", answer: "One Piece", imageUrl: "one_piece_2.jpg" },
    { id: 311, category: "characters", answer: "Ace", imageUrl: "ace.jpg"},
    { id: 312, category: "characters", answer: "Sabo", imageUrl: "sabo.jpg"},
    { id: 313, category: "characters", answer: "Shanks", imageUrl: "shanks.jpg"},
    { id: 314, category: "characters", answer: "Tashigi", imageUrl: "tashigi.jpg"},
    { id: 315, category: "characters", answer: "Smoker", imageUrl: "smoker.jpg"},
    { id: 316, category: "characters", answer: "Kizaru", imageUrl: "kizaru.jpg"},
    { id: 317, category: "characters", answer: "Luffy", imageUrl: "luffy.jpg"},
    { id: 318, category: "characters", answer: "Luffy Pesadelo", imageUrl: "luffy_pesadelo.jpg"},
    { id: 319, category: "characters", answer: "Zoro", imageUrl: "zoro.jpg"},
    { id: 320, category: "characters", answer: "Nami", imageUrl: "nami.jpg"},
    { id: 321, category: "characters", answer: "Usopp", imageUrl: "usopp.jpg"},
    { id: 322, category: "characters", answer: "Sanji", imageUrl: "sanji.jpg" },
    { id: 323, category: "characters", answer: "Chopper", imageUrl: "chopper.jpg" },
    { id: 324, category: "characters", answer: "Sogeking", imageUrl: "sogeking.jpg" },
    { id: 325, category: "characters", answer: "Luke Skywalker", imageUrl: "luke_skywalker.jpg" },
    { id: 326, category: "characters", answer: "Darth Vader", imageUrl: "darth_vader.jpg" },
    { id: 327, category: "characters", answer: "Yoda", imageUrl: "yoda.jpg" },
    { id: 328, category: "characters", answer: "Obi-Wan Kenobi", imageUrl: "obi_wan_kenobi.jpg" },
    { id: 329, category: "characters", answer: "Han Solo", imageUrl: "han_solo.jpg" },
    { id: 330, category: "characters", answer: "Chewbacca", imageUrl: "chewbacca.jpg" },
    { id: 331, category: "characters", answer: "R2-D2", imageUrl: "r2_d2.jpg" },
    { id: 332, category: "characters", answer: "C-3PO", imageUrl: "c_3po.jpg" },
    { id: 333, category: "characters", answer: "Boba Fett", imageUrl: "boba_fett.jpg" },
    { id: 334, category: "characters", answer: "Mandaloriano", imageUrl: "mandaloriano.jpg" },
    { id: 335, category: "characters", answer: "Gaara", imageUrl: "gaara.jpg" },
    { id: 336, category: "characters", answer: "Sasuke Uchiha", imageUrl: "sasuke_uchiha.jpg" },
    { id: 337, category: "characters", answer: "Itachi Uchiha", imageUrl: "itachi_uchiha.jpg" },
    { id: 338, category: "characters", answer: "Naruto", imageUrl: "naruto_uzumaki.jpg" },
    { id: 339, category: "characters", answer: "Sakura", imageUrl: "sakura_haruno.jpg" },
    { id: 340, category: "characters", answer: "Kakashi", imageUrl: "kakashi_hatake.jpg" },
    { id: 341, category: "characters", answer: "Rasa", imageUrl: "rasa.jpg" },
    { id: 342, category: "characters", answer: "Tobirama", imageUrl: "tobirama.jpg" },
    { id: 343, category: "characters", answer: "Minato", imageUrl: "minato.jpg" },
    { id: 344, category: "characters", answer: "Jiraiya", imageUrl: "jiraiya.jpg" },
    { id: 345, category: "characters", answer: "Orochimaru", imageUrl: "orochimaru.jpg" },
    { id: 346, category: "characters", answer: "Orochimaru", imageUrl: "orochimaru_2.jpg" },
    { id: 347, category: "characters", answer: "Madara Uchiha", imageUrl: "madara_uchiha.jpg" },
    { id: 348, category: "characters", answer: "Madara Uchiha", imageUrl: "madara_uchiha_2.jpg" },
    { id: 349, category: "characters", answer: "Obito Uchiha", imageUrl: "obito_uchiha.jpg" },
    { id: 350, category: "characters", answer: "Obito Uchiha", imageUrl: "obito_uchiha_2.jpg" },
    { id: 351, category: "characters", answer: "Tobi", imageUrl: "tobi.jpg" },
    { id: 352, category: "pokemon", answer: "Greninja", imageUrl: "greninja.jpg" },
    { id: 353, category: "pokemon", answer: "Ash Greninja", imageUrl: "ash_greninja.jpg" },
    { id: 354, category: "pokemon", answer: "Infernape", imageUrl: "infernape.jpg" },
    { id: 355, category: "pokemon", answer: "Empoleon", imageUrl: "empoleon.jpg" },
    { id: 356, category: "pokemon", answer: "Torterra", imageUrl: "torterra.jpg" },
    { id: 357, category: "pokemon", answer: "Lucario", imageUrl: "lucario.jpg" },
    { id: 358, category: "pokemon", answer: "Cresselia", imageUrl: "cresselia.jpg" },
    { id: 359, category: "characters", answer: "Sage", imageUrl: "sage.jpg" },
    { id: 360, category: "characters", answer: "Jett", imageUrl: "jett.jpg" },
    { id: 361, category: "characters", answer: "Phoenix", imageUrl: "phoenix.jpg" },
    { id: 362, category: "characters", answer: "Sova", imageUrl: "sova.jpg" },
    { id: 363, category: "characters", answer: "Reyna", imageUrl: "reyna.jpg" },
    { id: 364, category: "characters", answer: "Cypher", imageUrl: "cypher.jpg" },
    { id: 365, category: "characters", answer: "Eren", imageUrl: "eren.jpg" },
    { id: 366, category: "characters", answer: "Mikasa", imageUrl: "mikasa.jpg" },
    { id: 367, category: "characters", answer: "Armin", imageUrl: "armin.jpg" },
    { id: 368, category: "characters", answer: "Levi", imageUrl: "levi.jpg" },
    { id: 369, category: "characters", answer: "Erwin", imageUrl: "erwin.jpg" },
    { id: 370, category: "characters", answer: "Hange", imageUrl: "hange.jpg" },
    { id: 371, category: "characters", answer: "Edward Elric", imageUrl: "edward_elric.jpg" },
    { id: 372, category: "characters", answer: "Alphonse Elric", imageUrl: "alphonse_elric.jpg" },
    { id: 373, category: "characters", answer: "Roy Mustang", imageUrl: "roy_mustang.jpg" },
    { id: 374, category: "characters", answer: "Scar", imageUrl: "scar.jpg" },
    { id: 375, category: "characters", answer: "Luxúria", imageUrl: "luxuria.jpg" },
    { id: 376, category: "characters", answer: "Inveja", imageUrl: "inveja.jpg" },
    { id: 377, category: "characters", answer: "Gon", imageUrl: "gon.jpg" },
    { id: 378, category: "characters", answer: "Killua", imageUrl: "killua.jpg" },
    { id: 379, category: "characters", answer: "Kurapika", imageUrl: "kurapika.jpg" },
    { id: 380, category: "characters", answer: "L", imageUrl: "l.jpg"},
    { id: 381, category: "characters", answer: "Light Yagami", imageUrl: "light_yagami.jpg" },
    { id: 382, category: "characters", answer: "Near", imageUrl: "near.jpg" },
    { id: 383, category: "characters", answer: "Misa Amane", imageUrl: "misa_amane.jpg" },
    { id: 384, category: "characters", answer: "Mello", imageUrl: "mello.jpg" },
    { id: 385, category: "games", answer:"Rocket League", imageUrl: "rocket_league.jpg" },
    { id: 386, category:"games", answer:"Among Us", imageUrl: "among_us.jpg" },
    { id: 387, category:"games", answer:"Fall Guys", imageUrl: "fall_guys.jpg" },
    { id: 388, category:"games", answer:"The Sims", imageUrl: "the_sims.jpg" },
    { id: 389, category:"games", answer:"The Sims 2", imageUrl: "the_sims_2.jpg" },
    { id: 390, category:"games", answer:"The Sims 3", imageUrl: "the_sims_3.jpg" },
    { id: 391, category:"games", answer:"The Sims 4", imageUrl: "the_sims_4.jpg" },
    { id: 392, category:"games", answer:"Spore", imageUrl: "spore.jpg" },
    { id: 393, category:"games", answer:"2XKO", imageUrl: "2xko.jpg" },
    { id: 394, category:"games", answer:"GTA San Andreas", imageUrl: "gta_san_andreas.jpg" },
    { id: 395, category:"games", answer:"GTA Vice City", imageUrl: "gta_vice_city.jpg" },
    { id: 396, category:"games", answer:"Red Dead Redemption", imageUrl: "red_dead_redemption.jpg" },
    { id: 397, category:"games", answer:"Mortal Kombat 3", imageUrl: "mortal_kombat_3.jpg" },
    { id: 398, category:"games", answer:"Mortal Kombat 11", imageUrl: "mortal_kombat_11.jpg" },
    { id: 399, category:"games", answer:"Street Fighter 2", imageUrl: "street_fighter_2.jpg" },
    { id: 400, category:"games", answer:"Street Fighter 6", imageUrl: "street_fighter_6.jpg" }
];