import { Question } from "../types/Question";

export const questionList: Question[] = [
    { id: 1, category: "anime", answers: ["Naruto"], imageUrl: "naruto.jpg" },
    { id: 2, category: "anime", answers: ["One Piece"], imageUrl: "one_piece.jpg" },
    { id: 3, category: "anime", answers: ["Attack on Titan", "Shingeki no Kyojin"], imageUrl: "attack_on_titan.jpg" },
    { id: 4, category: "anime", answers: ["Fullmetal Alchemist", "Fullmetal Alchemist Brotherhood"], imageUrl: "fullmetal_alchemist.jpg" },
    { id: 5, category: "anime", answers: ["Death Note"], imageUrl: "death_note.jpg" },
    { id: 6, category: "anime", answers: ["Dragon Ball Z"], imageUrl: "dragon_ball_z.jpg" },
    { id: 7, category: "anime", answers: ["My Hero Academia", "Boku no Hero Academia"], imageUrl: "my_hero_academia.jpg" },
    { id: 8, category: "anime", answers: ["Demon Slayer", "Kimetsu no Yaiba"], imageUrl: "demon_slayer.jpg" },
    { id: 9, category: "anime", answers: ["Tokyo Ghoul"], imageUrl: "tokyo_ghoul.jpg" },
    { id: 10, category: "anime", answers: ["Sword Art Online"], imageUrl: "sword_art_online.jpg" },
    { id: 11, category: "anime", answers: ["Bleach"], imageUrl: "bleach.jpg" },
    { id: 12, category: "anime", answers: ["Fairy Tail"], imageUrl: "fairy_tail.jpg" },
    { id: 13, category: "anime", answers: ["Cowboy Bebop"], imageUrl: "cowboy_bepop.jpg" },
    { id: 14, category: "anime", answers: ["Neon Genesis Evangelion", "Evangelion"], imageUrl: "neon_genesis_evangelion.jpg" },
    { id: 15, category: "anime", answers: ["JoJo's Bizarre Adventure", "Jojo"], imageUrl: "jojo.jpg" },
    { id: 16, category: "anime", answers: ["Hunter x Hunter"], imageUrl: "hunter_x_hunter.jpg" },
    { id: 17, category: "anime", answers: ["Black Clover"], imageUrl: "black_clover.jpg" },
    { id: 18, category: "anime", answers: ["Gintama"], imageUrl: "gintama.jpg" },
    { id: 19, category: "anime", answers: ["Mob Psycho 100"], imageUrl: "mob_psycho_100.jpg" },
    { id: 20, category: "anime", answers: ["The Seven Deadly Sins", "Nanatsu no Taizai"], imageUrl: "seven_deadly_sins.jpg" },
    { id: 21, category: "pokemon", answers: ["Bulbasaur", "Bulbassauro"], imageUrl: "bulbasaur.jpg" },
    { id: 22, category: "pokemon", answers: ["Ivysaur", "Ivyssauro"], imageUrl: "ivysaur.jpg" },
    { id: 23, category: "pokemon", answers: ["Venusaur", "Venussauro"], imageUrl: "venusaur.jpg" },
    { id: 24, category: "pokemon", answers: ["Charmander"], imageUrl: "charmander.jpg" },
    { id: 25, category: "pokemon", answers: ["Charmeleon"], imageUrl: "charmeleon.jpg" },
    { id: 26, category: "pokemon", answers: ["Charizard"], imageUrl: "charizard.jpg" },
    { id: 27, category: "pokemon", answers: ["Squirtle"], imageUrl: "squirtle.jpg" },
    { id: 28, category: "pokemon", answers: ["Wartortle"], imageUrl: "wartortle.jpg" },
    { id: 29, category: "pokemon", answers: ["Blastoise"], imageUrl: "blastoise.jpg" },
    { id: 30, category: "pokemon", answers: ["Pikachu"], imageUrl: "pikachu.jpg" },
    { id: 31, category: "pokemon", answers: ["Raichu"], imageUrl: "raichu.jpg" },
    { id: 32, category: "pokemon", answers: ["Jigglypuff"], imageUrl: "jigglypuff.jpg" },
    { id: 33, category: "pokemon", answers: ["Meowth"], imageUrl: "meowth.jpg" },
    { id: 34, category: "pokemon", answers: ["Psyduck"], imageUrl: "psyduck.jpg" },
    { id: 35, category: "pokemon", answers: ["Machop"], imageUrl: "machop.jpg" },
    { id: 36, category: "pokemon", answers: ["Geodude"], imageUrl: "geodude.jpg" },
    { id: 37, category: "pokemon", answers: ["Eevee"], imageUrl: "eevee.jpg" },
    { id: 38, category: "pokemon", answers: ["Snorlax"], imageUrl: "snorlax.jpg" },
    { id: 39, category: "pokemon", answers: ["Mewtwo"], imageUrl: "mewtwo.jpg" },
    { id: 40, category: "pokemon", answers: ["Magikarp"], imageUrl: "magikarp.jpg" },
    { id: 41, category: "characters", answers: ["Mario", "Super Mario", "Mario Bros"], imageUrl: "mario.jpg" },
    { id: 42, category: "characters", answers: ["Luigi", "Luigi Bros"], imageUrl: "luigi.jpg" },
    { id: 43, category: "characters", answers: ["Shadow", "Shadow the Hedgehog"], imageUrl: "shadow.jpg" },
    { id: 44, category: "characters", answers: ["Link"], imageUrl: "link.jpg" },
    { id: 45, category: "characters", answers: ["Ash Ketchum", "Ash"], imageUrl: "ash_ketchum.jpg" },
    { id: 46, category: "characters", answers: ["Killer Bee", "Bee", "Killer B", "B"], imageUrl: "killer_bee.jpg" },
    { id: 47, category: "characters", answers: ["Goku Black", "Black", "Zamasu"], imageUrl: "goku_black.jpg" },
    { id: 48, category: "characters", answers: ["Sailor Moon"], imageUrl: "sailor_moon.jpg" },
    { id: 49, category: "characters", answers: ["Batman"], imageUrl: "batman.jpg" },
    { id: 50, category: "characters", answers: ["Homem de Ferro", "Iron Man", "Tony Stark"], imageUrl: "homem_de_ferro.jpg" },
    { id: 51, category: "characters", answers: ["Capitão América", "Captain America", "Steve Rogers"], imageUrl: "capitao_america.jpg" },
    { id: 52, category: "characters", answers: ["Thor"], imageUrl: "thor.jpg" },
    { id: 53, category: "characters", answers: ["Lara Croft"], imageUrl: "lara_croft.jpg" },
    { id: 54, category: "characters", answers: ["Kratos"], imageUrl: "kratos.jpg" },
    { id: 55, category: "characters", answers: ["Master Chief", "Chief"], imageUrl: "master_chief.jpg" },
    { id: 56, category: "characters", answers: ["Solid Snake", "Snake"], imageUrl: "solid_snake.jpg" },
    { id: 57, category: "characters", answers: ["Yoshi"], imageUrl: "yoshi.jpg" },
    { id: 58, category: "characters", answers: ["Donkey Kong"], imageUrl: "donkey_kong.jpg" },
    { id: 59, category: "characters", answers: ["Kirby"], imageUrl: "kirby.jpg" },
    { id: 60, category: "characters", answers: ["Rock Lee", "Lee"], imageUrl: "rock_lee.jpg" },
    { id: 61, category: "movies", answers: ["Inception", "A Origem"], imageUrl: "inception.jpg" },
    { id: 62, category: "movies", answers: ["Interstelar", "Interestelar"], imageUrl: "interstelar.jpg" },
    { id: 63, category: "movies", answers: ["De Volta Para o Futuro", "Back to the Future"], imageUrl: "de_volta_para_o_futuro.jpg" },
    { id: 64, category: "movies", answers: ["Forrest Gump"], imageUrl: "forrest_gump.jpg" },
    { id: 66, category: "movies", answers: ["Pulp Fiction"], imageUrl: "pulp_fiction.jpg" },
    { id: 67, category: "movies", answers: ["Star Wars", "Guerra nas Estrelas"], imageUrl: "star_wars.jpg" },
    { id: 68, category: "movies", answers: ["Matrix"], imageUrl: "matrix.jpg" },
    { id: 69, category: "movies", answers: ["Titanic"], imageUrl: "titanic.jpg" },
    { id: 70, category: "movies", answers: ["Gladiador"], imageUrl: "gladiador.jpg" },
    { id: 71, category: "movies", answers: ["Jurassic Park"], imageUrl: "jurassic_park.jpg" },
    { id: 72, category: "movies", answers: ["Avatar"], imageUrl: "avatar.jpg" },
    { id: 73, category: "movies", answers: ["O Rei Leão"], imageUrl: "o_rei_leao.jpg" },
    { id: 74, category: "movies", answers: ["Homem-Aranha 3", "Spider-Man 3", "Spiderman 3", "Spider Man 3"], imageUrl: "homem_aranha_3.jpg" },
    { id: 75, category: "movies", answers: ["Coringa"], imageUrl: "coringa.jpg" },
    { id: 76, category: "movies", answers: ["Os Vingadores", "The Avengers", "Avengers", "Vingadores"], imageUrl: "os_vingadores.jpg" },
    { id: 77, category: "movies", answers: ["Harry Potter"], imageUrl: "harry_potter.jpg" },
    { id: 78, category: "movies", answers: ["Brilho Eterno de uma Mente Sem Lembranças"], imageUrl: "brilho_eterno.jpg" },
    { id: 79, category: "movies", answers: ["Cidadão Kane"], imageUrl: "cidadao_kane.jpg" },
    { id: 80, category: "movies", answers: ["O Grande Lebowski"], imageUrl: "o_grande_lebowski.jpg" },
    { id: 81, category: "games", answers: ["The Witcher 3"], imageUrl: "the_witcher_3.jpg" },
    { id: 82, category: "games", answers: ["Red Dead Redemption 2", "RDR2"], imageUrl: "red_dead_redemption_2.jpg" },
    { id: 83, category: "games", answers: ["The Last of Us", "Last of Us"], imageUrl: "the_last_of_us.jpg" },
    { id: 84, category: "games", answers: ["God of War"], imageUrl: "god_of_war.jpg" },
    { id: 85, category: "games", answers: ["Minecraft"], imageUrl: "minecraft.jpg" },
    { id: 86, category: "games", answers: ["Fortnite"], imageUrl: "fortnite.jpg" },
    { id: 87, category: "games", answers: ["League of Legends", "LoL"], imageUrl: "league_of_legends.jpg" },
    { id: 88, category: "games", answers: ["Overwatch"], imageUrl: "overwatch.jpg" },
    { id: 89, category: "games", answers: ["Cyberpunk 2077", "CP2077"], imageUrl: "cyberpunk_2077.jpg" },
    { id: 90, category: "games", answers: ["Elden Ring"], imageUrl: "elden_ring.jpg" },
    { id: 91, category: "games", answers: ["Hollow Knight"], imageUrl: "hollow_knight.jpg" },
    { id: 92, category: "games", answers: ["Dark Souls 2"], imageUrl: "dark_souls_2.jpg" },
    { id: 93, category: "games", answers: ["Super Mario Odyssey", "Mario Odyssey"], imageUrl: "super_mario_odyssey.jpg" },
    { id: 94, category: "games", answers: ["Pokémon Yellow", "Pokémon", "Pocket Monsters"], imageUrl: "pokemon_yellow.jpg" },
    { id: 95, category: "games", answers: ["Doom Eternal"], imageUrl: "doom_eternal.jpg" },
    { id: 96, category: "games", answers: ["Resident Evil 7", "RE7", "Resident Evil VII", "Resident Evil Biohazard"], imageUrl: "resident_evil_7.jpg" },
    { id: 97, category: "games", answers: ["Final Fantasy 7", "FF7", "Final Fantasy VII"], imageUrl: "final_fantasy_7.jpg" },
    { id: 98, category: "games", answers: ["Terraria"], imageUrl: "terraria.jpg" },
    { id: 99, category: "games", answers: ["Sonic 2", "Sonic the Hedgehog 2", "Sonic the Hedgehog", "Sonic"], imageUrl: "sonic_2.jpg" },
    { id: 100, category: "games", answers: ["Cuphead"], imageUrl: "cuphead.jpg" },
    { id: 101, category: "music", answers: ["Queen"], imageUrl: "queen.jpg" },
    { id: 102, category: "music", answers: ["The Beatles", "Beatles"], imageUrl: "the_beatles.jpg" },
    { id: 103, category: "music", answers: ["Michael Jackson", "MJ"], imageUrl: "michael_jackson.jpg" },
    { id: 104, category: "music", answers: ["Madonna"], imageUrl: "madonna.jpg" },
    { id: 105, category: "music", answers: ["Elvis Presley"], imageUrl: "elvis_presley.jpg" },
    { id: 106, category: "music", answers: ["Beyoncé"], imageUrl: "beyonce.jpg" },
    { id: 107, category: "music", answers: ["Taylor Swift"], imageUrl: "taylor_swift.jpg" },
    { id: 108, category: "music", answers: ["Adele"], imageUrl: "adele.jpg" },
    { id: 109, category: "music", answers: ["Drake"], imageUrl: "drake.jpg" },
    { id: 110, category: "music", answers: ["Player Tauz", "Tauz"], imageUrl: "player_tauz.jpg" },
    { id: 111, category: "music", answers: ["Katy Perry"], imageUrl: "katy_perry.jpg" },
    { id: 112, category: "music", answers: ["Bruno Mars"], imageUrl: "bruno_mars.jpg" },
    { id: 113, category: "music", answers: ["Rihanna"], imageUrl: "rihanna.jpg" },
    { id: 114, category: "music", answers: ["Eminem"], imageUrl: "eminem.jpg" },
    { id: 115, category: "music", answers: ["Billie Eilish"], imageUrl: "billie_eilish.jpg" },
    { id: 116, category: "music", answers: ["Coldplay"], imageUrl: "coldplay.jpg" },
    { id: 117, category: "music", answers: ["Anitta"], imageUrl: "anitta.jpg" },
    { id: 118, category: "music", answers: ["Linkin Park"], imageUrl: "linkin_park.jpg" },
    { id: 119, category: "music", answers: ["Nirvana"], imageUrl: "nirvana.jpg" },
    { id: 120, category: "music", answers: ["Luan Santana"], imageUrl: "luan_santana.jpg" },
    { id: 121, category: "tvShows", answers: ["Breaking Bad"], imageUrl: "breaking_bad.jpg" },
    { id: 122, category: "tvShows", answers: ["Game of Thrones"], imageUrl: "game_of_thrones.jpg" },
    { id: 123, category: "tvShows", answers: ["Stranger Things"], imageUrl: "stranger_things.jpg" },
    { id: 124, category: "tvShows", answers: ["The Crown"], imageUrl: "the_crown.jpg" },
    { id: 125, category: "tvShows", answers: ["The Mandalorian", "O Mandaloriano", "Mandaloriano"], imageUrl: "the_mandalorian.jpg" },
    { id: 126, category: "tvShows", answers: ["Friends"], imageUrl: "friends.jpg" },
    { id: 127, category: "tvShows", answers: ["The Office"], imageUrl: "the_office.jpg" },
    { id: 128, category: "tvShows", answers: ["Sherlock"], imageUrl: "sherlock.jpg" },
    { id: 129, category: "tvShows", answers: ["Westworld"], imageUrl: "westworld.jpg" },
    { id: 130, category: "tvShows", answers: ["Peaky Blinders"], imageUrl: "peaky_blinders.jpg" },
    { id: 131, category: "tvShows", answers: ["The Witcher"], imageUrl: "the_witcher.jpg" },
    { id: 132, category: "tvShows", answers: ["House of Cards"], imageUrl: "house_of_cards.jpg" },
    { id: 133, category: "tvShows", answers: ["Better Call Saul"], imageUrl: "better_call_saul.jpg" },
    { id: 134, category: "tvShows", answers: ["Black Mirror"], imageUrl: "black_mirror.jpg" },
    { id: 135, category: "tvShows", answers: ["Narcos"], imageUrl: "narcos.jpg" },
    { id: 136, category: "tvShows", answers: ["The Boys"], imageUrl: "the_boys.jpg" },
    { id: 137, category: "tvShows", answers: ["Loki"], imageUrl: "loki.jpg" },
    { id: 138, category: "tvShows", answers: ["WandaVision", "Wanda Vision"], imageUrl: "wandavision.jpg" },
    { id: 139, category: "tvShows", answers: ["Lupin"], imageUrl: "lupin.jpg" },
    { id: 140, category: "tvShows", answers: ["Round 6", "Squid Game", "Round Six"], imageUrl: "round_6.jpg" },
    { id: 141, category: "cartoons", answers: ["Bob Esponja", "SpongeBob SquarePants", "SpongeBob"], imageUrl: "bob_esponja.jpg" },
    { id: 142, category: "cartoons", answers: ["Pica-Pau", "Woody Woodpecker"], imageUrl: "pica_pau.jpg" },
    { id: 143, category: "cartoons", answers: ["Tom e Jerry"], imageUrl: "tom_e_jerry.jpg" },
    { id: 144, category: "cartoons", answers: ["O Incrível Mundo de Gumball", "The Amazing World of Gumball", "Gumball"], imageUrl: "o_incrivel_mundo_de_gumball.jpg" },
    { id: 145, category: "cartoons", answers: ["Hora de Aventura"], imageUrl: "hora_de_aventura.jpg" },
    { id: 146, category: "cartoons", answers: ["Os Padrinhos Mágicos", "The Fairly OddParents", "Padrinhos Mágicos"], imageUrl: "os_padrinhos_magicos.jpg" },
    { id: 147, category: "cartoons", answers: ["Os Simpsons", "The Simpsons", "Simpsons"], imageUrl: "os_simpsons.jpg" },
    { id: 148, category: "cartoons", answers: ["Futurama"], imageUrl: "futurama.jpg" },
    { id: 149, category: "cartoons", answers: ["Rick e Morty", "Rick and Morty"], imageUrl: "rick_e_morty.jpg" },
    { id: 150, category: "cartoons", answers: ["Ursinho Pooh"], imageUrl: "ursinho_pooh.jpg" },
    { id: 151, category: "cartoons", answers: ["Apenas um Show", "Regular Show"], imageUrl: "apenas_um_show.jpg" },
    { id: 152, category: "cartoons", answers: ["Sonic Satam", "Sonic the Hedgehog SatAM"], imageUrl: "sonic_satam.jpg" },
    { id: 153, category: "cartoons", answers: ["As Meninas Superpoderosas"], imageUrl: "as_meninas_superpoderosas.jpg" },
    { id: 154, category: "cartoons", answers: ["Ben 10"], imageUrl: "ben_10.jpg" },
    { id: 155, category: "cartoons", answers: ["Phineas e Ferb"], imageUrl: "phineas_e_ferb.jpg" },
    { id: 156, category: "cartoons", answers: ["Slugterrâneo"], imageUrl: "slugterraneo.jpg" },
    { id: 157, category: "cartoons", answers: ["Kid vs Cat", "Kid versus Cat"], imageUrl: "kid_vs_cat.jpg" },
    { id: 158, category: "cartoons", answers: ["Liga da Justiça", "Justice League", ""], imageUrl: "liga_da_justica.jpg" },
    { id: 159, category: "cartoons", answers: ["Super Choque", "Static Shock"], imageUrl: "super_choque.jpg" },
    { id: 160, category: "cartoons", answers: ["Peixonauta"], imageUrl: "peixonauta.jpg" },
    { id: 161, category: "logo", answers: ["Nike"], imageUrl: "nike.jpg" },
    { id: 162, category: "logo", answers: ["Adidas"], imageUrl: "adidas.jpg" },
    { id: 163, category: "logo", answers: ["Apple"], imageUrl: "apple.jpg" },
    { id: 164, category: "logo", answers: ["NVIDIA"], imageUrl: "nvidia.jpg" },
    { id: 165, category: "logo", answers: ["Starbucks"], imageUrl: "starbucks.jpg" },
    { id: 166, category: "logo", answers: ["Pepsi"], imageUrl: "pepsi.jpg" },
    { id: 167, category: "logo", answers: ["Kabum"], imageUrl: "kabum.jpg" },
    { id: 168, category: "logo", answers: ["AMD"], imageUrl: "amd.jpg" },
    { id: 169, category: "logo", answers: ["Android"], imageUrl: "android.jpg" },
    { id: 170, category: "logo", answers: ["Microsoft"], imageUrl: "microsoft.jpg" },
    { id: 171, category: "logo", answers: ["Facebook"], imageUrl: "facebook.jpg" },
    { id: 172, category: "logo", answers: ["Twitter"], imageUrl: "twitter.jpg" },
    { id: 173, category: "logo", answers: ["YouTube Music"], imageUrl: "youtube_music.jpg" },
    { id: 174, category: "logo", answers: ["Amazon"], imageUrl: "amazon.jpg" },
    { id: 175, category: "logo", answers: ["Samsung"], imageUrl: "samsung.jpg" },
    { id: 176, category: "logo", answers: ["Toyota"], imageUrl: "toyota.jpg" },
    { id: 177, category: "logo", answers: ["BMW", "Bayerische Motoren Werke"], imageUrl: "bmw.jpg" },
    { id: 178, category: "logo", answers: ["Volkswagen", "VW"], imageUrl: "volkswagen.jpg" },
    { id: 179, category: "logo", answers: ["Audi"], imageUrl: "audi.jpg" },
    { id: 180, category: "logo", answers: ["Honda"], imageUrl: "honda.jpg" },
    { id: 181, category: "flag", answers: ["Brasil", "Brazil"], imageUrl: "brasil.jpg" },
    { id: 182, category: "flag", answers: ["Estados Unidos", "United States", "USA", "EUA"], imageUrl: "estados_unidos.jpg" },
    { id: 183, category: "flag", answers: ["Japão"], imageUrl: "japao.jpg" },
    { id: 184, category: "flag", answers: ["Alemanha"], imageUrl: "alemanha.jpg" },
    { id: 185, category: "flag", answers: ["Egito"], imageUrl: "egito.jpg" },
    { id: 186, category: "flag", answers: ["Itália"], imageUrl: "italia.jpg" },
    { id: 187, category: "flag", answers: ["Reino Unido"], imageUrl: "reino_unido.jpg" },
    { id: 188, category: "flag", answers: ["Canadá"], imageUrl: "canada.jpg" },
    { id: 189, category: "flag", answers: ["China"], imageUrl: "china.jpg" },
    { id: 190, category: "flag", answers: ["Índia"], imageUrl: "india.jpg" },
    { id: 191, category: "flag", answers: ["Suriname"], imageUrl: "suriname.jpg" },
    { id: 192, category: "flag", answers: ["Austrália"], imageUrl: "australia.jpg" },
    { id: 193, category: "flag", answers: ["México"], imageUrl: "mexico.jpg" },
    { id: 194, category: "flag", answers: ["Argentina"], imageUrl: "argentina.jpg" },
    { id: 195, category: "flag", answers: ["África do Sul"], imageUrl: "africa_do_sul.jpg" },
    { id: 196, category: "flag", answers: ["Coreia do Norte"], imageUrl: "coreia_do_norte.jpg" },
    { id: 197, category: "flag", answers: ["Espanha"], imageUrl: "espanha.jpg" },
    { id: 198, category: "flag", answers: ["Suécia"], imageUrl: "suecia.jpg" },
    { id: 199, category: "flag", answers: ["Noruega"], imageUrl: "noruega.jpg" },
    { id: 200, category: "flag", answers: ["Suiça"], imageUrl: "suica.jpg" },
    { id: 201, category: "soccer", answers: ["Barcelona", "Barça"], imageUrl: "barcelona.jpg" },
    { id: 202, category: "soccer", answers: ["Real Madrid"], imageUrl: "real_madrid.jpg" },
    { id: 203, category: "soccer", answers: ["Manchester United"], imageUrl: "manchester_united.jpg" },
    { id: 204, category: "soccer", answers: ["Liverpool"], imageUrl: "liverpool.jpg" },
    { id: 205, category: "soccer", answers: ["Juventus"], imageUrl: "juventus.jpg" },
    { id: 206, category: "soccer", answers: ["Fluminense", "Flu"], imageUrl: "fluminense.jpg" },
    { id: 207, category: "soccer", answers: ["Corinthians", "Timão", "Sport Club Corinthians Paulista"], imageUrl: "corinthians.jpg" },
    { id: 208, category: "soccer", answers: ["LDU", "Liga Deportiva Universitaria", "Liga de Quito", "LDU Quito"], imageUrl: "ldu.jpg" },
    { id: 209, category: "soccer", answers: ["Santos", "Santos FC"], imageUrl: "santos.jpg" },
    { id: 210, category: "soccer", answers: ["Inter de Milão"], imageUrl: "inter_de_milao.jpg" },
    { id: 211, category: "soccer", answers: ["Boca Júniors"], imageUrl: "boca_juniors.jpg" },
    { id: 212, category: "soccer", answers: ["Chelsea"], imageUrl: "chelsea.jpg" },
    { id: 213, category: "soccer", answers: ["Arsenal"], imageUrl: "arsenal.jpg" },
    { id: 214, category: "soccer", answers: ["River Plate"], imageUrl: "river_plate.jpg" },
    { id: 215, category: "soccer", answers: ["Independiente"], imageUrl: "independiente.jpg" },
    { id: 216, category: "soccer", answers: ["San Lorenzo"], imageUrl: "san_lorenzo.jpg" },
    { id: 217, category: "soccer", answers: ["Grêmio"], imageUrl: "gremio.jpg" },
    { id: 218, category: "soccer", answers: ["Internacional"], imageUrl: "internacional.jpg" },
    { id: 219, category: "soccer", answers: ["Atlético Mineiro", "Galo"], imageUrl: "atletico_mineiro.jpg" },
    { id: 220, category: "soccer", answers: ["Bayer Leverkusen"], imageUrl: "bayer_leverkusen.jpg" },
    { id: 221, category: "fruits", answers: ["Maçã"], imageUrl: "maca.jpg" },
    { id: 222, category: "fruits", answers: ["Banana"], imageUrl: "banana.jpg" },
    { id: 223, category: "fruits", answers: ["Laranja"], imageUrl: "laranja.jpg" },
    { id: 224, category: "fruits", answers: ["Morango"], imageUrl: "morango.jpg" },
    { id: 225, category: "fruits", answers: ["Abacaxi"], imageUrl: "abacaxi.jpg" },
    { id: 226, category: "fruits", answers: ["Uva"], imageUrl: "uva.jpg" },
    { id: 227, category: "fruits", answers: ["Melancia"], imageUrl: "melancia.jpg" },
    { id: 228, category: "fruits", answers: ["Pera"], imageUrl: "pera.jpg" },
    { id: 229, category: "fruits", answers: ["Tangerina"], imageUrl: "tangerina.jpg" },
    { id: 230, category: "fruits", answers: ["Framboesa"], imageUrl: "framboesa.jpg" },
    { id: 231, category: "animals", answers: ["Onça"], imageUrl: "onca.jpg" },
    { id: 232, category: "animals", answers: ["Urso Polar"], imageUrl: "urso_polar.jpg" },
    { id: 233, category: "animals", answers: ["Coala"], imageUrl: "coala.jpg" },
    { id: 234, category: "animals", answers: ["Hipopótamo"], imageUrl: "hipopotamo.jpg" },
    { id: 235, category: "animals", answers: ["Rinoceronte"], imageUrl: "rinoceronte.jpg" },
    { id: 236, category: "animals", answers: ["Chita"], imageUrl: "chita.jpg" },
    { id: 237, category: "animals", answers: ["Boto"], imageUrl: "boto.jpg" },
    { id: 238, category: "animals", answers: ["Águia"], imageUrl: "aguia.jpg" },
    { id: 239, category: "animals", answers: ["Falcão"], imageUrl: "falcao.jpg" },
    { id: 240, category: "animals", answers: ["Crocodilo"], imageUrl: "crocodilo.jpg" },
    { id: 241, category: "animals", answers: ["Golfinho"], imageUrl: "golfinho.jpg" },
    { id: 242, category: "animals", answers: ["Jacaré"], imageUrl: "jacare.jpg" },
    { id: 243, category: "characters", answers: ["Pepsiman"], imageUrl: "pepsiman.jpg" },
    { id: 244, category: "characters", answers: ["Shisui Uchiha", "Shisui"], imageUrl: "shisui_uchiha.jpg" },
    { id: 245, category: "characters", answers: ["Jaco"], imageUrl: "jaco.jpg" },
    { id: 246, category: "characters", answers: ["Law", "Trafalgar Law", "D. Water Law", "D. Water Law Trafalgar"], imageUrl: "law.jpg" },
    { id: 247, category: "characters", answers: ["Gol D. Roger", "Gold Roger", "Roger"], imageUrl: "gol_d_roger.jpg" },
    { id: 248, category: "characters", answers: ["Cooler", "Coola"], imageUrl: "cooler.jpg" },
    { id: 249, category: "characters", answers: ["Kefla", "Kafla"], imageUrl: "kefla.jpg" },
    { id: 250, category: "characters", answers: ["Nail"], imageUrl: "nail.jpg" },
    { id: 251, category: "characters", answers: ["Boa Hancock", "Hancock", "Boa"], imageUrl: "boa_hancock.jpg" },
    { id: 252, category: "characters", answers: ["Turles"], imageUrl: "turles.jpg" },
    { id: 253, category: "characters", answers: ["Zarbon"], imageUrl: "zarbon.jpg" },
    { id: 254, category: "characters", answers: ["Bardock"], imageUrl: "bardock.jpg" },
    { id: 255, category: "games", answers: ["Pepsiman"], imageUrl: "pepsiman_ps1.jpg" },
    { id: 256, category: "games", answers: ["Minecraft Legends"], imageUrl: "minecraft_legends.jpg" },
    { id: 257, category: "games", answers: ["Minecraft Dungeons"], imageUrl: "minecraft_dungeons.jpg" },
    { id: 258, category: "games", answers: ["Minecraft Story Mode"], imageUrl: "minecraft_story_mode.jpg" },
    { id: 259, category: "games", answers: ["Forza Horizon"], imageUrl: "forza_horizon.jpg" },
    { id: 260, category: "games", answers: ["Forza Horizon 3", "Forza Horizon"], imageUrl: "forza_horizon_3.jpg" },
    { id: 261, category: "games", answers: ["Need For Speed Most Wanted", "Need for Speed"], imageUrl: "need_for_speed_most_wanted.jpg" },
    { id: 262, category: "games", answers: ["Need For Speed Underground 2", "Need for Speed", "Need for Speed Underground"], imageUrl: "need_for_speed_underground_2.jpg" },
    { id: 263, category: "games", answers: ["Midnight Club 3", "Midnight Club", "Midnight Club 3 DUB Edition"], imageUrl: "midnight_club_3.jpg" },
    { id: 264, category: "games", answers: ["Burnout Paradise", "Burnout"], imageUrl: "burnout_paradise.jpg" },
    { id: 265, category: "games", answers: ["Burnout Revenge", "Burnout"], imageUrl: "burnout_revenge.jpg" },
    { id: 266, category: "pokemon", answers: ["Celebi"], imageUrl: "celebi.jpg" },
    { id: 267, category: "pokemon", answers: ["Jirachi"], imageUrl: "jirachi.jpg" },
    { id: 268, category: "pokemon", answers: ["Deoxys"], imageUrl: "deoxys.jpg" },
    { id: 269, category: "pokemon", answers: ["Phione"], imageUrl: "phione.jpg" },
    { id: 270, category: "pokemon", answers: ["Manaphy"], imageUrl: "manaphy.jpg" },
    { id: 271, category: "pokemon", answers: ["Darkrai"], imageUrl: "darkrai.jpg" },
    { id: 272, category: "pokemon", answers: ["Totodile"], imageUrl: "totodile.jpg" },
    { id: 273, category: "pokemon", answers: ["Cyndaquil"], imageUrl: "cyndaquil.jpg" },
    { id: 274, category: "pokemon", answers: ["Chikorita"], imageUrl: "chikorita.jpg" },
    { id: 275, category: "pokemon", answers: ["Mudkip"], imageUrl: "mudkip.jpg" },
    { id: 276, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto.jpg" },
    { id: 277, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_2.jpg" },
    { id: 278, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_3.jpg" },
    { id: 279, category: "pokemon", answers: ["Ditto"], imageUrl: "ditto_4.jpg" },
    { id: 280, category: "pokemon", answers: ["Heracross"], imageUrl: "heracross.jpg" },
    { id: 281, category: "characters", answers: ["Cell. Jr", "Cell Júnior"], imageUrl: "cell_jr.jpg" },
    { id: 282, category: "characters", answers: ["Mestre Karin", "Karin"], imageUrl: "mestre_karin.jpg" },
    { id: 283, category: "characters", answers: ["Yamcha"], imageUrl: "yamcha.jpg" },
    { id: 284, category: "characters", answers: ["Tenshinhan", "Tien"], imageUrl: "tenshinhan.jpg" },
    { id: 285, category: "characters", answers: ["Chaos", "Chiaotzu"], imageUrl: "chaos.jpg" },
    { id: 286, category: "characters", answers: ["Knuckles"], imageUrl: "knuckles.jpg" },
    { id: 287, category: "characters", answers: ["Tails", "Miles", "Miles Prower", "Miles Tails Prower"], imageUrl: "tails.jpg" },
    { id: 288, category: "characters", answers: ["Amy Rose", "Amy"], imageUrl: "amy_rose.jpg" },
    { id: 289, category: "characters", answers: ["Big the Cat", "Big"], imageUrl: "big_the_cat.jpg" },
    { id: 290, category: "characters", answers: ["Metal Sonic", "Metal"], imageUrl: "metal_sonic.jpg" },
    { id: 291, category: "characters", answers: ["Zamasu"], imageUrl: "zamasu.jpg" },
    { id: 292, category: "characters", answers: ["Hitto", "Hit"], imageUrl: "hitto.jpg" },
    { id: 293, category: "characters", answers: ["Fusão Zamasu", "Fused Zamasu", "Zamasu Fundido", "Zamasu"], imageUrl: "fusao_zamasu.jpg" },
    { id: 294, category: "characters", answers: ["Kid Buu", "Kid Boo", "Majin Buu", "Boo", "Buu"], imageUrl: "kid_buu.jpg" },
    { id: 295, category: "characters", answers: ["Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "majin_buu.jpg" },
    { id: 296, category: "characters", answers: ["Super Buu", "Super Boo", "Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "super_buu.jpg" },
    { id: 297, category: "characters", answers: ["Ultra Buu", "Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "ultra_buu.jpg" },
    { id: 298, category: "characters", answers: ["Super Buuhan", "Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "super_buuhan.jpg" },
    { id: 299, category: "characters", answers: ["Super Buutenks", "Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "super_buutenks.jpg" },
    { id: 300, category: "characters", answers: ["Super Buucolo", "Majin Buu", "Majin Boo", "Boo", "Buu"], imageUrl: "super_buucolo.jpg" },
    { id: 301, category: "characters", answers: ["Vegetto", "Vegito", "Vegerot"], imageUrl: "vegetto.jpg" },
    { id: 302, category: "characters", answers: ["Gogeta"], imageUrl: "gogeta.jpg" },
    { id: 303, category: "characters", answers: ["Broly"], imageUrl: "broly.jpg" },
    { id: 304, category: "characters", answers: ["Broly"], imageUrl: "broly_dbs.jpg" },
    { id: 305, category: "anime", answers: ["Dragon Ball"], imageUrl: "dragon_ball.jpg" },
    { id: 306, category: "anime", answers: ["Dragon Ball Super"], imageUrl: "dragon_ball_super.jpg" },
    { id: 307, category: "anime", answers: ["Dragon Ball GT"], imageUrl: "dragon_ball_gt.jpg" },
    { id: 308, category: "anime", answers: ["Naruto Shippuden"], imageUrl: "naruto_shippuden.jpg" },
    { id: 309, category: "anime", answers: ["Boruto"], imageUrl: "boruto.jpg" },
    { id: 310, category: "anime", answers: ["One Piece"], imageUrl: "one_piece_2.jpg" },
    { id: 311, category: "characters", answers: ["Ace", "Portgas D. Ace"], imageUrl: "ace.jpg" },
    { id: 312, category: "characters", answers: ["Sabo", "Monkey D. Sabo"], imageUrl: "sabo.jpg" },
    { id: 313, category: "characters", answers: ["Shanks"], imageUrl: "shanks.jpg" },
    { id: 314, category: "characters", answers: ["Tashigi"], imageUrl: "tashigi.jpg" },
    { id: 315, category: "characters", answers: ["Smoker", "Captain Smoker", "Capitão Smoker"], imageUrl: "smoker.jpg" },
    { id: 316, category: "characters", answers: ["Kizaru", "Borsalino", "Borsalino Kizaru"], imageUrl: "kizaru.jpg" },
    { id: 317, category: "characters", answers: ["Luffy", "Monkey D. Luffy"], imageUrl: "luffy.jpg" },
    { id: 318, category: "characters", answers: ["Luffy Pesadelo", "Nightmare Luffy", "Luffy"], imageUrl: "luffy_pesadelo.jpg" },
    { id: 319, category: "characters", answers: ["Zoro", "Roronoa Zoro"], imageUrl: "zoro.jpg" },
    { id: 320, category: "characters", answers: ["Nami"], imageUrl: "nami.jpg" },
    { id: 321, category: "characters", answers: ["Usopp"], imageUrl: "usopp.jpg" },
    { id: 322, category: "characters", answers: ["Sanji", "Vinsmoke Sanji"], imageUrl: "sanji.jpg" },
    { id: 323, category: "characters", answers: ["Chopper"], imageUrl: "chopper.jpg" },
    { id: 324, category: "characters", answers: ["Sogeking"], imageUrl: "sogeking.jpg" },
    { id: 325, category: "characters", answers: ["Luke Skywalker", "Luke", "Skywalker"], imageUrl: "luke_skywalker.jpg" },
    { id: 326, category: "characters", answers: ["Darth Vader", "Anakin Skywalker", "Anakin", "Skywalker"], imageUrl: "darth_vader.jpg" },
    { id: 327, category: "characters", answers: ["Yoda"], imageUrl: "yoda.jpg" },
    { id: 328, category: "characters", answers: ["Obi-Wan Kenobi", "Ben Kenobi", "Obi-Wan"], imageUrl: "obi_wan_kenobi.jpg" },
    { id: 329, category: "characters", answers: ["Han Solo", "Han", "Solo"], imageUrl: "han_solo.jpg" },
    { id: 330, category: "characters", answers: ["Chewbacca"], imageUrl: "chewbacca.jpg" },
    { id: 331, category: "characters", answers: ["R2-D2"], imageUrl: "r2_d2.jpg" },
    { id: 332, category: "characters", answers: ["C-3PO"], imageUrl: "c_3po.jpg" },
    { id: 333, category: "characters", answers: ["Boba Fett"], imageUrl: "boba_fett.jpg" },
    { id: 334, category: "characters", answers: ["Mandaloriano", "The Mandalorian", "Din Djarin"], imageUrl: "mandaloriano.jpg" },
    { id: 335, category: "characters", answers: ["Gaara"], imageUrl: "gaara.jpg" },
    { id: 336, category: "characters", answers: ["Sasuke Uchiha", "Sasuke"], imageUrl: "sasuke_uchiha.jpg" },
    { id: 337, category: "characters", answers: ["Itachi Uchiha", "Itachi"], imageUrl: "itachi_uchiha.jpg" },
    { id: 338, category: "characters", answers: ["Naruto Uzumaki", "Naruto"], imageUrl: "naruto_uzumaki.jpg" },
    { id: 339, category: "characters", answers: ["Sakura", "Sakura Haruno"], imageUrl: "sakura_haruno.jpg" },
    { id: 340, category: "characters", answers: ["Kakashi", "Kakashi Hatake"], imageUrl: "kakashi_hatake.jpg" },
    { id: 341, category: "characters", answers: ["Rasa"], imageUrl: "rasa.jpg" },
    { id: 342, category: "characters", answers: ["Tobirama", "Tobirama Senju"], imageUrl: "tobirama.jpg" },
    { id: 343, category: "characters", answers: ["Minato", "Minato Namikaze"], imageUrl: "minato.jpg" },
    { id: 344, category: "characters", answers: ["Jiraiya"], imageUrl: "jiraiya.jpg" },
    { id: 345, category: "characters", answers: ["Orochimaru"], imageUrl: "orochimaru.jpg" },
    { id: 346, category: "characters", answers: ["Orochimaru"], imageUrl: "orochimaru_2.jpg" },
    { id: 347, category: "characters", answers: ["Madara Uchiha", "Madara"], imageUrl: "madara_uchiha.jpg" },
    { id: 348, category: "characters", answers: ["Madara Uchiha", "Madara"], imageUrl: "madara_uchiha_2.jpg" },
    { id: 349, category: "characters", answers: ["Obito Uchiha", "Obito"], imageUrl: "obito_uchiha.jpg" },
    { id: 350, category: "characters", answers: ["Obito Uchiha", "Obito"], imageUrl: "obito_uchiha_2.jpg" },
    { id: 351, category: "characters", answers: ["Tobi", "Obito Uchiha", "Obito", "Madara", "Madara Uchiha"], imageUrl: "tobi.jpg" },
    { id: 352, category: "pokemon", answers: ["Greninja"], imageUrl: "greninja.jpg" },
    { id: 353, category: "pokemon", answers: ["Ash Greninja", "Greninja"], imageUrl: "ash_greninja.jpg" },
    { id: 354, category: "pokemon", answers: ["Infernape"], imageUrl: "infernape.jpg" },
    { id: 355, category: "pokemon", answers: ["Empoleon"], imageUrl: "empoleon.jpg" },
    { id: 356, category: "pokemon", answers: ["Torterra"], imageUrl: "torterra.jpg" },
    { id: 357, category: "pokemon", answers: ["Lucario"], imageUrl: "lucario.jpg" },
    { id: 358, category: "pokemon", answers: ["Cresselia"], imageUrl: "cresselia.jpg" },
    { id: 359, category: "characters", answers: ["Sage"], imageUrl: "sage.jpg" },
    { id: 360, category: "characters", answers: ["Jett"], imageUrl: "jett.jpg" },
    { id: 361, category: "characters", answers: ["Phoenix"], imageUrl: "phoenix.jpg" },
    { id: 362, category: "characters", answers: ["Sova"], imageUrl: "sova.jpg" },
    { id: 363, category: "characters", answers: ["Reyna"], imageUrl: "reyna.jpg" },
    { id: 364, category: "characters", answers: ["Cypher"], imageUrl: "cypher.jpg" },
    { id: 365, category: "characters", answers: ["Eren"], imageUrl: "eren.jpg" },
    { id: 366, category: "characters", answers: ["Mikasa"], imageUrl: "mikasa.jpg" },
    { id: 367, category: "characters", answers: ["Armin"], imageUrl: "armin.jpg" },
    { id: 368, category: "characters", answers: ["Levi"], imageUrl: "levi.jpg" },
    { id: 369, category: "characters", answers: ["Erwin"], imageUrl: "erwin.jpg" },
    { id: 370, category: "characters", answers: ["Hange"], imageUrl: "hange.jpg" },
    { id: 371, category: "characters", answers: ["Edward Elric", "Edward"], imageUrl: "edward_elric.jpg" },
    { id: 372, category: "characters", answers: ["Alphonse Elric", "Al", "Alphonse"], imageUrl: "alphonse_elric.jpg" },
    { id: 373, category: "characters", answers: ["Roy Mustang", "Mustang", "Roy"], imageUrl: "roy_mustang.jpg" },
    { id: 374, category: "characters", answers: ["Scar"], imageUrl: "scar.jpg" },
    { id: 375, category: "characters", answers: ["Luxúria", "Lust"], imageUrl: "luxuria.jpg" },
    { id: 376, category: "characters", answers: ["Inveja", "Envy"], imageUrl: "inveja.jpg" },
    { id: 377, category: "characters", answers: ["Gon", "Gon Freecss"], imageUrl: "gon.jpg" },
    { id: 378, category: "characters", answers: ["Killua", "Killua Zoldyck"], imageUrl: "killua.jpg" },
    { id: 379, category: "characters", answers: ["Kurapika"], imageUrl: "kurapika.jpg" },
    { id: 380, category: "characters", answers: ["L", "Ryuzaki"], imageUrl: "l.jpg" },
    { id: 381, category: "characters", answers: ["Light Yagami", "Kira", "Light"], imageUrl: "light_yagami.jpg" },
    { id: 382, category: "characters", answers: ["Near", "N"], imageUrl: "near.jpg" },
    { id: 383, category: "characters", answers: ["Misa Amane"], imageUrl: "misa_amane.jpg" },
    { id: 384, category: "characters", answers: ["Mello", "M"], imageUrl: "mello.jpg" },
    { id: 385, category: "games", answers: ["Rocket League"], imageUrl: "rocket_league.jpg" },
    { id: 386, category: "games", answers: ["Among Us"], imageUrl: "among_us.jpg" },
    { id: 387, category: "games", answers: ["Fall Guys"], imageUrl: "fall_guys.jpg" },
    { id: 388, category: "games", answers: ["The Sims"], imageUrl: "the_sims.jpg" },
    { id: 389, category: "games", answers: ["The Sims 2", "Sims 2", "The Sims"], imageUrl: "the_sims_2.jpg" },
    { id: 390, category: "games", answers: ["The Sims 3", "Sims 3", "The Sims"], imageUrl: "the_sims_3.jpg" },
    { id: 391, category: "games", answers: ["The Sims 4", "Sims 4", "The Sims"], imageUrl: "the_sims_4.jpg" },
    { id: 392, category: "games", answers: ["Spore"], imageUrl: "spore.jpg" },
    { id: 393, category: "games", answers: ["2XKO"], imageUrl: "2xko.jpg" },
    { id: 394, category: "games", answers: ["GTA San Andreas"], imageUrl: "gta_san_andreas.jpg" },
    { id: 395, category: "games", answers: ["GTA Vice City"], imageUrl: "gta_vice_city.jpg" },
    { id: 396, category: "games", answers: ["Red Dead Redemption"], imageUrl: "red_dead_redemption.jpg" },
    { id: 397, category: "games", answers: ["Mortal Kombat 3", "Mortal Kombat"], imageUrl: "mortal_kombat_3.jpg" },
    { id: 398, category: "games", answers: ["Mortal Kombat 11", "Mortal Kombat"], imageUrl: "mortal_kombat_11.jpg" },
    { id: 399, category: "games", answers: ["Street Fighter 2", "Street Fighter"], imageUrl: "street_fighter_2.jpg" },
    { id: 400, category: "games", answers: ["Street Fighter 6", "Street Fighter"], imageUrl: "street_fighter_6.jpg" },
    { id: 401, category: "movies", answers: ["Alien"], imageUrl: "alien.jpg" },
    { id: 402, category: "movies", answers: ["The Dark Knight", "Batman: O Cavaleiro das Trevas"], imageUrl: "the_dark_knight.jpg" },
    { id: 403, category: "movies", answers: ["Homem de Ferro", "Iron Man"], imageUrl: "homem_de_ferro_filme.jpg" },
    { id: 404, category: "movies", answers: ["Homem de Ferro 2", "Iron Man 2"], imageUrl: "homem_de_ferro_2_filme.jpg" },
    { id: 405, category: "movies", answers: ["Homem de Ferro 3", "Iron Man 3"], imageUrl: "homem_de_ferro_3_filme.jpg" },
    { id: 406, category: "movies", answers: ["Capitão América: O Primeiro Vingador", "Captain America: The First Avenger"], imageUrl: "capitao_america_o_primeiro_vingador.jpg" },
    { id: 407, category: "movies", answers: ["Capitão América: O Soldado Invernal", "Captain America: The Winter Soldier"], imageUrl: "capitao_america_o_soldado_invernal.jpg" },
    { id: 408, category: "movies", answers: ["Capitão América: Guerra Civil", "Captain America: Civil War"], imageUrl: "capitao_america_guerra_civil.jpg" },
    { id: 409, category: "movies", answers: ["Thor"], imageUrl: "thor_filme.jpg" },
    { id: 410, category: "movies", answers: ["Thor: O Mundo Sombrio", "Thor: The Dark World", "Thor 2"], imageUrl: "thor_o_mundo_sombrio.jpg" },
    { id: 411, category: "movies", answers: ["Thor: Ragnarok"], imageUrl: "thor_ragnarok.jpg" },
    { id: 413, category: "movies", answers: ["Vingadores: Era de Ultron", "Avengers: Age of Ultron", "Ultron"], imageUrl: "vingadores_era_de_ultron.jpg" },
    { id: 414, category: "movies", answers: ["Vingadores: Guerra Infinita", "Avengers: Infinity War"], imageUrl: "vingadores_guerra_infinita.jpg" },
    { id: 415, category: "movies", answers: ["Vingadores: Ultimato", "Avengers: Endgame"], imageUrl: "vingadores_ultimato.jpg" },
    { id: 416, category: "movies", answers: ["Guardiões da Galáxia", "Guardians of the Galaxy"], imageUrl: "guardiões_da_galaxia.jpg" },
    { id: 417, category: "movies", answers: ["Guardiões da Galáxia Vol. 2", "Guardians of the Galaxy Vol. 2", "Guardiões da Galáxia 2"], imageUrl: "guardiões_da_galaxia_vol_2.jpg" },
    { id: 418, category: "movies", answers: ["Homem-Formiga", "Ant-Man"], imageUrl: "homem_formiga.jpg" },
    { id: 419, category: "movies", answers: ["John Wick"], imageUrl: "john_wick.jpg" },
    { id: 420, category: "movies", answers: ["Mad Max: Estrada da Fúria", "Mad Max Fury Road", "Mad Max"], imageUrl: "mad_max_estrada_da_furia.jpg" },
    { id: 421, category: "movies", answers: ["Missão Impossível", "Mission Impossible"], imageUrl: "missao_impossivel.jpg" },
    { id: 422, category: "movies", answers: ["300"], imageUrl: "300.jpg" },
    { id: 423, category: "movies", answers: ["O Exterminador do Futuro", "Terminator"], imageUrl: "terminator.jpg" },
    { id: 424, category: "movies", answers: ["Duro de Matar", "Die Hard"], imageUrl: "duro_de_matar.jpg" },
    { id: 425, category: "movies", answers: ["O Grande Truque", "The Prestige"], imageUrl: "o_grande_truque.jpg" },
    { id: 426, category: "movies", answers: ["O Iluminado", "The Shining"], imageUrl: "o_iluminado.jpg" },
    { id: 427, category: "movies", answers: ["Invocação do Mal", "The Conjuring"], imageUrl: "invocacao_do_mal.jpg" },
    { id: 428, category: "movies", answers: ["Pânico", "Scream"], imageUrl: "panico.jpg" },
    { id: 429, category: "movies", answers: ["O Chamado", "The Ring"], imageUrl: "o_chamado.jpg" },
    { id: 430, category: "movies", answers: ["Corra!", "Get Out"], imageUrl: "corra.jpg" },
    { id: 431, category: "movies", answers: ["Blade Runner 2049", "Blade Runner"], imageUrl: "blade_runner_2049.jpg" },
    { id: 432, category: "movies", answers: ["Duna", "Dune"], imageUrl: "duna.jpg" },
    { id: 433, category: "movies", answers: ["Gravidade", "Gravity"], imageUrl: "gravidade.jpg" },
    { id: 434, category: "movies", answers: ["Ex Machina"], imageUrl: "ex_machina.jpg" },
    { id: 435, category: "movies", answers: ["Se Beber, Não Case!", "The Hangover"], imageUrl: "se_beber_nao_case.jpg" },
    { id: 436, category: "movies", answers: ["As Branquelas", "White Chicks"], imageUrl: "as_branquelas.jpg" },
    { id: 437, category: "movies", answers: ["Superbad"], imageUrl: "superbad.jpg" },
    { id: 438, category: "movies", answers: ["Click"], imageUrl: "click.jpg" },
    { id: 439, category: "movies", answers: ["Gente Grande", "Grown Ups"], imageUrl: "gente_grande.jpg" },
    { id: 440, category: "movies", answers: ["Seven", "Seven: Os Sete Crimes Capitais"], imageUrl: "seven.jpg" },
    { id: 441, category: "movies", answers: ["Ilha do Medo", "Shutter Island"], imageUrl: "ilha_do_medo.jpg" },
    { id: 442, category: "movies", answers: ["Garota Exemplar", "Gone Girl"], imageUrl: "garota_exemplar.jpg" },
    { id: 443, category: "movies", answers: ["O Sexto Sentido", "The Sixth Sense"], imageUrl: "o_sexto_sentido.jpg" },
    { id: 444, category: "movies", answers: ["Corpo Fechado", "Unbreakable"], imageUrl: "corpo_fechado.jpg" },
    { id: 445, category: "movies", answers: ["O Poderoso Chefão", "The Godfather"], imageUrl: "o_poderoso_chefao.jpg" },
    { id: 446, category: "movies", answers: ["Um Sonho de Liberdade", "The Shawshank Redemption"], imageUrl: "um_sonho_de_liberdade.jpg" },
    { id: 447, category: "movies", answers: ["Cisne Negro", "Black Swan"], imageUrl: "cisne_negro.jpg" },
    { id: 449, category: "movies", answers: ["O Lobo de Wall Street", "The Wolf of Wall Street"], imageUrl: "o_lobo_de_wall_street.jpg" },
    { id: 450, category: "movies", answers: ["Clube da Luta", "Fight Club"], imageUrl: "clube_da_luta.jpg" },
    { id: 451, category: "tvShows", answers: ["Todo Mundo Odeia o Chris", "Chris", "Everybody Hates Chris"], imageUrl: "todo_mundo_odeia_o_chris.jpg" },
    { id: 452, category: "tvShows", answers: ["Todo Mundo Odeia o Chris", "Chris", "Everybody Hates Chris"], imageUrl: "todo_mundo_odeia_o_chris_2.jpg" },
    { id: 453, category: "tvShows", answers: ["Knuckles"], imageUrl: "knuckles_serie.jpg" },
    { id: 454, category: "tvShows", answers: ["Uma Família Perfeita", "Good American Family"], imageUrl: "uma_familia_perfeita.jpg" },
    { id: 455, category: "tvShows", answers: ["Dark"], imageUrl: "dark.jpg" },
    { id: 456, category: "tvShows", answers: ["How I Met Your Mother"], imageUrl: "how_i_met_your_mother.jpg" },
    { id: 457, category: "tvShows", answers: ["Brooklyn Nine-Nine", "Brooklyn 99"], imageUrl: "brooklyn_nine_nine.jpg" },
    { id: 458, category: "tvShows", answers: ["Vikings"], imageUrl: "vikings.jpg" },
    { id: 459, category: "characters", answers: ["Majin Kuu", "Kuu"], imageUrl: "majin_kuu.jpg" },
    { id: 460, category: "characters", answers: ["Majin Duu", "Duu"], imageUrl: "majin_duu.jpg" },
    { id: 461, category: "characters", answers: ["Kid Goku", "Goku"], imageUrl: "kid_goku.jpg" },
    { id: 462, category: "characters", answers: ["Yajirobe"], imageUrl: "yajirobe.jpg" },
    { id: 463, category: "characters", answers: ["Pilaf"], imageUrl: "pilaf.jpg" },
    { id: 464, category: "characters", answers: ["Orange Piccolo", "Piccolo", "Piccolo Laranja"], imageUrl: "piccolo.jpg" },
    { id: 465, category: "characters", answers: ["Raditz"], imageUrl: "raditz.jpg" },
    { id: 466, category: "characters", answers: ["Nappa"], imageUrl: "nappa.jpg" },
    { id: 467, category: "characters", answers: ["Dende"], imageUrl: "dende.jpg" },
    { id: 468, category: "characters", answers: ["Kami Sama", "Kami"], imageUrl: "kami_sama.jpg" },
    { id: 469, category: "characters", answers: ["Mr. Popo"], imageUrl: "mr_popo.jpg" },
    { id: 470, category: "characters", answers: ["Videl"], imageUrl: "videl.jpg" },
    { id: 471, category: "characters", answers: ["Piccolo"], imageUrl: "piccolo_2.jpg" },
    { id: 472, category: "characters", answers: ["Gohan"], imageUrl: "gohan.jpg" },
    { id: 473, category: "characters", answers: ["Goten"], imageUrl: "goten.jpg" },
    { id: 474, category: "characters", answers: ["Trunks"], imageUrl: "trunks.jpg" },
    { id: 475, category: "characters", answers: ["Bulma"], imageUrl: "bulma.jpg" },
    { id: 476, category: "characters", answers: ["Trunks", "Trunks do Futuro", "Mirai Trunks", "Future Trunks"], imageUrl: "trunks_do_futuro.jpg" },
    { id: 477, category: "characters", answers: ["Beast Gohan", "Gohan", "Gohan Fera"], imageUrl: "gohan_2.jpg" },
    { id: 478, category: "characters", answers: ["Androide 18", "Android 18"], imageUrl: "androide_18.jpg" },
    { id: 479, category: "characters", answers: ["Androide 17", "Android 17"], imageUrl: "androide_17.jpg" },
    { id: 480, category: "characters", answers: ["Mr. Satan", "Hércules", "Hercules"], imageUrl: "mr_satan.jpg" },
    { id: 481, category: "characters", answers: ["Dabura"], imageUrl: "dabura.jpg" }, 
    { id: 482, category: "characters", answers: ["Supremo Kaioshin", "Supreme Kai", "Kaioshin", "Shin"], imageUrl: "supremo_kaioshin.jpg" },
    { id: 483, category: "characters", answers: ["Bibidi"], imageUrl: "bibidi.jpg" }, 
    { id: 484, category: "characters", answers: ["Babidi"], imageUrl: "babidi.jpg" },
    { id: 485, category: "characters", answers: ["Goku", "Son Goku", "Goku SSJ4"], imageUrl: "goku_ssj4.jpg" },
    { id: 486, category: "soccer", answers: ["Uberaba"], imageUrl: "uberaba.jpg" },
    { id: 487, category: "soccer", answers: ["Cruzeiro", "Raposa"], imageUrl: "cruzeiro.jpg" },
    { id: 488, category: "soccer", answers: ["América Mineiro", "Coelho"], imageUrl: "america_mineiro.jpg" },
    { id: 489, category: "soccer", answers: ["Criciúma"], imageUrl: "criciuma.jpg" },
    { id: 490, category: "soccer", answers: ["Figueirense"], imageUrl: "figueirense.jpg" },
    { id: 491, category: "soccer", answers: ["Operário Ferroviário", "Operário"], imageUrl: "operario_ferroviario.jpg" },
    { id: 492, category: "soccer", answers: ["Coritiba"], imageUrl: "coritiba.jpg" },
    { id: 493, category: "soccer", answers: ["Athletico Paranaense", "Athletico-PR", "Furacão"], imageUrl: "athletico_paranaense.jpg"},
    { id: 494, category: "soccer", answers: ["Ceará"], imageUrl: "ceara.jpg" },
    { id: 495, category: "soccer", answers: ["Fortaleza"], imageUrl: "fortaleza.jpg" },
    { id: 496, category: "soccer", answers: ["Botafogo", "Botafogo de Futebol e Regatas", "Botafogo F.R", "Botafogo Futebol e Regatas", "Fogão"], imageUrl: "botafogo.jpg" },
    { id: 497, category: "soccer", answers: ["Vasco da Gama", "Vasco"], imageUrl: "vasco_da_gama.jpg" },
    { id: 498, category: "soccer", answers: ["Flamengo", "Clube de Regatas do Flamengo"], imageUrl: "flamengo.jpg" },
    { id: 499, category: "soccer", answers: ["São Paulo"], imageUrl: "sao_paulo.jpg" },
    { id: 500, category: "characters", answers: ["Pain", "Nagato", "Nagato Uzumaki"], imageUrl: "pain.jpg" },
    { id: 501, category: "characters", answers: ["Nagato", "Nagato Uzumaki", "Pain"], imageUrl: "nagato.jpg" },
    { id: 502, category: "characters", answers: ["Konan"], imageUrl: "konan.jpg" },
    { id: 503, category: "characters", answers: ["Tsunade"], imageUrl: "tsunade.jpg" },
    { id: 504, category: "characters", answers: ["Zetsu"], imageUrl: "zetsu.jpg" },
    { id: 505, category: "characters", answers: ["Hidan"], imageUrl: "hidan.jpg" },
    { id: 506, category: "characters", answers: ["Kakuzu"], imageUrl: "kakuzu.jpg" },
    { id: 507, category: "characters", answers: ["Deidara"], imageUrl: "deidara.jpg" },
    { id: 508, category: "characters", answers: ["Sasori"], imageUrl: "sasori.jpg" },
    { id: 509, category: "characters", answers: ["Kisame Hoshigaki", "Kisame"], imageUrl: "kisame_hoshigaki.jpg" },
    { id: 510, category: "characters", answers: ["Tobi", "Obito Uchiha", "Obito", "Madara", "Madara Uchiha"], imageUrl: "tobi_2.jpg" },
    { id: 511, category: "characters", answers: ["Tobi", "Obito Uchiha", "Obito", "Madara", "Madara Uchiha"], imageUrl: "tobi_3.jpg" },
    { id: 511, category: "pokemon", answers: ["Abra"], imageUrl: "abra.jpg" },
    { id: 512, category: "pokemon", answers: ["Kadabra"], imageUrl: "kadabra.jpg" },
    { id: 513, category: "pokemon", answers: ["Alakazam"], imageUrl: "alakazam.jpg" },
    { id: 514, category: "pokemon", answers: ["Tyranitar"], imageUrl: "tyranitar.jpg" },
    { id: 515, category: "pokemon", answers: ["Metagross"], imageUrl: "metagross.jpg" },
    { id: 516, category: "pokemon", answers: ["Salamence"], imageUrl: "salamence.jpg" },
    { id: 517, category: "pokemon", answers: ["Garchomp"], imageUrl: "garchomp.jpg" },
    { id: 518, category: "pokemon", answers: ["Hydreigon"], imageUrl: "hydreigon.jpg" },
    { id: 519, category: "pokemon", answers: ["Aegislash"], imageUrl: "aegislash.jpg" },
    { id: 520, category: "pokemon", answers: ["Dragapult"], imageUrl: "dragapult.jpg" },
    { id: 521, category: "characters", answers: ["Mirio Togata", "Mirio"], imageUrl: "mirio_togata.jpg" },
    { id: 522, category: "characters", answers: ["Tamaki Amajiki", "Tamaki"], imageUrl: "tamaki_amajiki.jpg" },
    { id: 523, category: "characters", answers: ["Nejire Hado", "Nejire"], imageUrl: "nejire_hado.jpg" },
    { id: 524, category: "characters", answers: ["All For One"], imageUrl: "all_for_one.jpg" },
    { id: 525, category: "characters", answers: ["Dabi"], imageUrl: "dabi.jpg" },
    { id: 526, category: "characters", answers: ["Himiko Toga", "Toga"], imageUrl: "himiko_toga.jpg" },
    { id: 527, category: "characters", answers: ["Shigaraki Tomura", "Tomura Shigaraki", "Shigaraki"], imageUrl: "shigaraki_tomura.jpg" },
    { id: 528, category: "characters", answers: ["Katsuki Bakugo", "Bakugo"], imageUrl: "katsuki_bakugo.jpg"},
    { id: 529, category: "characters", answers: ["Izuku Midoriya", "Deku"], imageUrl: "izuku_midoriya.jpg" },
    { id: 530, category: "characters", answers: ["Shoto Todoroki", "Todoroki"], imageUrl: "shoto_todoroki.jpg" },
    { id: 531, category: "characters", answers: ["Ochaco Uraraka", "Uraraka"], imageUrl: "ochaco_uraraka.jpg" },
    { id: 532, category: "characters", answers: ["Tenya Iida", "Iida"], imageUrl: "tenya_iida.jpg" },
    { id: 533, category: "characters", answers: ["All Might"], imageUrl: "all_might.jpg" },
    { id: 534, category: "characters", answers: ["Eraserhead", "Shota Aizawa", "Aizawa"], imageUrl: "shota_aizawa.jpg"},
    { id: 535, category: "characters", answers: ["Endeavor"], imageUrl: "endeavor.jpg" },
    { id: 536, category: "characters", answers: ["Stain"], imageUrl: "stain.jpg" },
    { id: 537, category: "characters", answers: ["Kenny McCormick", "Kenny"], imageUrl: "kenny.jpg" },
    { id: 538, category: "characters", answers: ["Eric Cartman", "Cartman"], imageUrl: "eric_cartman.jpg" },
    { id: 539, category: "characters", answers: ["Homer Simpson", "Homer"], imageUrl: "homer_simpson.jpg" },
    { id: 540, category: "characters", answers: ["Bart Simpson", "Bart"], imageUrl: "bart_simpson.jpg" },
    { id: 541, category: "characters", answers: ["Lisa Simpson", "Lisa"], imageUrl: "lisa_simpson.jpg" },
    { id: 542, category: "characters", answers: ["Marge Simpson", "Marge"], imageUrl: "marge_simpson.jpg" },
    { id: 543, category: "characters", answers: ["Mr. Burns", "Burns"], imageUrl: "mr_burns.jpg" },
    { id: 544, category: "characters", answers: ["Ned Flanders", "Flanders"], imageUrl: "ned_flanders.jpg" },
    { id: 545, category: "characters", answers: ["Krusty, o Palhaço", "Krusty"], imageUrl: "krusty_o_palhaco.jpg" },
    { id: 546, category: "characters", answers: ["Gumball Watterson", "Gumball"], imageUrl: "gumball_watterson.jpg" },
    { id: 547, category: "characters", answers: ["Darwin Watterson", "Darwin"], imageUrl: "darwin_watterson.jpg" },
    { id: 548, category: "characters", answers: ["Anais Watterson", "Anais"], imageUrl: "anais_watterson.jpg" },
    { id: 549, category: "characters", answers: ["Ricardo Watterson", "Richard Watterson", "Richard", "Ricardo"], imageUrl: "ricardo_watterson.jpg" },
    { id: 550, category: "characters", answers: ["Penny Fitzgerald", "Penny"], imageUrl: "penny_fitzgerald.jpg" },
    { id: 551, category: "characters", answers: ["Nicole Watterson", "Nicole"], imageUrl: "nicole_watterson.jpg" },
    { id: 552, category: "characters", answers: ["Walter White", "Mr White", "Heisenberg"], imageUrl: "walter_white.jpg"},
    { id: 553, category: "characters", answers: ["Jesse Pinkman", "Jesse"], imageUrl: "jesse_pinkman.jpg" },
    { id: 554, category: "characters", answers: ["Saul Goodman", "Saul", "Jimmy", "Jimmy McGill"], imageUrl: "saul_goodman.jpg" },
    { id: 555, category: "characters", answers: ["Gus Fring", "Gustavo Fring"], imageUrl: "gus_fring.jpg" },
    { id: 556, category: "characters", answers: ["Hank Schrader", "Hank"], imageUrl: "hank_schrader.jpg" },
    { id: 557, category: "characters", answers: ["Skyler White", "Skyler"], imageUrl: "skyler_white.jpg" },
    { id: 558, category: "characters", answers: ["Mike Ehrmantraut", "Mike"], imageUrl: "mike_ehrmantraut.jpg" },
    { id: 559, category: "characters", answers: ["Todd Alquist", "Todd"], imageUrl: "todd_alquist.jpg" },
    { id: 560, category: "characters", answers: ["Billy Bruto", "Billy Butcher", "Bruto", "Butcher"], imageUrl: "billy_bruto.jpg" },
    { id: 561, category: "characters", answers: ["Hughie Campbell", "Hughie"], imageUrl: "hughie_campbell.jpg" },
    { id: 562, category: "characters", answers: ["Starlight", "Annie January", "Luz Estrela"], imageUrl: "starlight.jpg" },
    { id: 563, category: "characters", answers: ["Homelander", "Capitao Pátria", "Pátria"], imageUrl: "homelander.jpg" },
    { id: 564, category: "characters", answers: ["Queen Maeve", "Rainha Maeve", "Maeve"], imageUrl: "queen_maeve.jpg" },
    { id: 565, category: "characters", answers: ["The Deep", "O Profundo"], imageUrl: "the_deep.jpg" },
    { id: 566, category: "characters", answers: ["Black Noir", "Noir"], imageUrl: "black_noir.jpg" },
    { id: 567, category: "characters", answers: ["A Train", "Trem Bala"], imageUrl: "a_train.jpg" },
    { id: 568, category: "characters", answers: ["Kurama", "Kyuubi", "Nine-Tails", "Nove Caudas", "Raposa de Nove Caudas"], imageUrl: "kurama.jpg" },
    { id: 569, category: "characters", answers: ["Shukaku", "One-Tail", "Uma Cauda", "Tanuki de Uma Cauda"], imageUrl: "shukaku.jpg" },
    { id: 570, category: "characters", answers: ["Son Goku", "Four-Tails", "Quatro Caudas", "Javali de Quatro Caudas"], imageUrl: "son_goku.jpg" },
    { id: 571, category: "characters", answers: ["Gyuki", "Eight-Tails", "Oito Caudas", "Boi de Oito Caudas"], imageUrl: "gyuki.jpg"},
    { id: 572, category: "characters", answers: ["Juubi", "Ten-Tails", "Dez Caudas"], imageUrl: "juubi.jpg"},
    { id: 573, category: "games", answers: ["Crash Bandicoot", "Crash"], imageUrl: "crash_bandicoot.jpg" },
    { id: 574, category: "games", answers: ["Crash Bandicoot 3: Warped", "Crash Bandicoot 3", "Crash 3", "Crash Bandicoot Warped"], imageUrl: "crash_bandicoot_3.jpg" },
    { id: 575, category: "games", answers: ["Crash Team Racing", "CTR"], imageUrl: "crash_team_racing.jpg" },
    { id: 576, category: "games", answers: ["Crash Nitro Kart"], imageUrl: "crash_nitro_kart.jpg" },
    { id: 577, category: "games", answers: ["Mario Party"], imageUrl: "mario_party.jpg" },
    { id: 578, category: "games", answers: ["Mario Kart 64", "Mario Kart"], imageUrl: "mario_kart_64.jpg" },
    { id: 579, category: "games", answers: ["Pokémon: Let's Go, Eevee / Pikachu!", "Pokemon Let's Go", "Pokémon Lets Go Eevee", "Pokémon Lets Go Pikachu"], imageUrl: "pokemon_lets_go.jpg" },
    { id: 581, category: "games", answers: ["Shadow The Hedgehog"], imageUrl: "shadow_the_hedgehog.jpg" },
    { id: 582, category: "games", answers: ["Sonic Unleashed"], imageUrl: "sonic_unleashed.jpg" },
    { id: 583, category: "music", answers: ["Tim Maia"], imageUrl: "tim_maia.jpg" },
    { id: 584, category: "music", answers: ["Cazuza"], imageUrl: "cazuza.jpg" },
    { id: 585, category: "music", answers: ["Legião Urbana"], imageUrl: "legiao_urbana.jpg" },
    { id: 586, category: "music", answers: ["Barão Vermelho"], imageUrl: "barao_vermelho.jpg" },
    { id: 587, category: "music", answers: ["Os Mamanonas Assassinas", "Mamonas Assassinas"], imageUrl: "mamonas_assassinas.jpg" },
    { id: 588, category: "flag", answers: ["França"], imageUrl: "franca.jpg" },
    { id: 589, category: "flag", answers: ["Romania"], imageUrl: "romania.jpg" },
    { id: 590, category: "flag", answers: ["Bélgica", "Belgium"], imageUrl: "belgica.jpg" },
    { id: 591, category: "flag", answers: ["Chade", "Chad"], imageUrl: "chade.jpg" },
    { id: 592, category: "characters", answers: ["Sonic The Werehog", "Werehog", "Sonic"], imageUrl: "sonic_werehog.jpg" },
    { id: 593, category: "characters", answers: ["Silver The Hedgehog", "Silver"], imageUrl: "silver_the_hedgehog.jpg" },
    { id: 594, category: "characters", answers: ["Asta"], imageUrl: "asta.jpg" },
    { id: 595, category: "characters", answers: ["Yuno"], imageUrl: "yuno.jpg" },
    { id: 596, category: "characters", answers: ["Kamado Tanjiro", "Tanjiro"], imageUrl: "tanjiro.jpg" },
    { id: 597, category: "characters", answers: ["Kamado Nezuko", "Nezuko"], imageUrl: "nezuko.jpg" },
    { id: 598, category: "characters", answers: ["Zenitsu Agatsuma", "Zenitsu"], imageUrl: "zenitsu.jpg" },
    { id: 599, category: "characters", answers: ["Inosuke Hashibira", "Inosuke"], imageUrl: "inosuke.jpg" },
    { id: 600, category: "characters", answers: ["Giyu Tomioka", "Giyu"], imageUrl: "giyu_tomioka.jpg"}
];